### PR TITLE
Fix else-statement bug in make_orog task; fix model_config bug for ensemble forecasts; remove obsolete physics suites; get WE2E tests to run on cheyenne

### PR DESCRIPTION
**Pull request by gsketefian**
This PR must be merged simultaneously with PR#[24](https://github.com/ufs-community/ufs-srweather-app/pull/24) into ufs-community/ufs-srweather-app which contains updates to the external repo hashes and the physics suites for which to build the forecast model.

### Bugs fixed:
* In exregional_make_orog.sh, remove the else-statement that causes the script to exit if the suite is not FV3_RRFS_v1beta.
* In exregional_run_fcst.sh, remove lines that create a symlink in the run directory to the model_configure file in the cycle directory.  These lines seem to have been inadvertantly reintroduced into the script and cause ensemble forecasts to fail.
 
### Other modifications:
* Remove suites FV3_GSD_SAR_v1 and FV3_RRFS_v0 from workflow since they are no longer in ufs-weather-model.  Also remove the WE2E test configuration files for these suites (config.regional_013.sh and config.regional_016.sh).
* In exregional_make_orog.sh, for the RRFS_v1beta suite, modify the command that copies the orography statistics files needed by the drag parameterization such that only files matching *_ls*.nc and *_ss*.nc are copied instead of everything (because the source directory may contain other files that do not need to be copied).
* In the WE2E configuration file for the RRFS_v1beta suite (config.FV3_RRFS_v1beta.sh), change the location where the additional orography files needed by this suite are copied from to a common location rather than a user directory.
* Remove unused script create_model_config_files.sh.
* Rename the function (and file) create_model_config_file(.sh) to create_model_configure_file(.sh) because the file that this function creates is called model_configure, not model_config.
* Modify WE2E test configuration files as well as the test run script (tests/run_experiments.sh) to get the tests to run more easily on cheyenne.  Still need to make a manual change to the settings in run_experiments.sh, but this made it possible to run the tests.

## TESTS CONDUCTED:
Ran all 26 WE2E tests both **on hera and cheyenne**.  24 of the 26 succeeded.  Details:
* regional_010 failed, but it was already broken.
* user_download_extrn_files failed.  It seems to have failed to obtain the external model files from NOMADS (and this step is done during workflow generation, not as part of any workflow task).  This test is completely unrelated to this PR, so the failure may have already existed in the develop branch.
* The remaining 24 tests (including the one for the FV3_RRFS_v1beta suite) succeeded without problems.

Note that the FV3_RRFS_v1beta suite was also tested on the GSD_HRRR3km grid.  This failed at around hour 4 (for a 6-hour forecast) with a very non-informative error.  This test was also tried previously with hash 8165575 from the NCAR fork of ufs-weather-model (in the dtc/develop branch), and that finished successfully.  Not clear what changed between these two versions of ufs-weather-model.

## OTHER CONTRIBUTORS:
@JeffBeck-NOAA

### CODE REVIEW

**Comment by gsketefian** [comment]
This has been successfully tested on hera.  Please test on other platforms if you like.  Otherwise, it's ready to merge (simultaneously with PR#[24](https://github.com/ufs-community/ufs-srweather-app/pull/24) into ufs-community/ufs-srweather-app.

**Comment by JeffBeck-NOAA** [comment]
Testing on Jet now.

**Review by JeffBeck-NOAA — APPROVED** [review]
@gsketefian After a successful build of the release/public-v2 FV3 code, two tests succeeded on Jet: one with FV3_GSD_SAR, another with FV3_RRFS_v1beta, the second with staged orog files. I updated the RRFS_v1beta baseline test with the following:

#On jet:
#GWD_RRFS_v1beta_BASEDIR="/lfs4/BMC/wrfruc/FV3LAM_pregen/orog"

@gsketefian Feel free to update the baseline test with these lines and merge your two PRs.

**Comment by gsketefian** [comment]
The WE2E tests passed on both hera and cheyenne, so I'm going to merge this.  @JulieSchramm to run the tests on cheyenne, you need to change STMP and PTMP in the file tests/run_experiments.sh.  I haven't gotten around to making those arguments to the script yet.  Please let me know if you need help.

**Pull request merged**
