### PR TITLE
Maximize RRFS_CONUS_[25,13,3]km grids so they span as much of HRRR CONUS domain as possible

### PR DESCRIPTION
**Pull request by gsketefian**
### Main changes:
* Change grid parameters for the RRFS_COUNS_25km, RRFS_CONUS_13km, and RRFS_CONUS_3km grids so that they span as much of the HRRR CONUS domain as possible.  Note that this is done without regard to whether NX and NY are evenly divisible by LAYOUT_X and LAYOUT_Y because these restrictions were recently removed from the forecast model.
* Remove several checks on the grid parameters.  These are:
  (1) The check on whether NX and NY are evenly divisible by LAYOUT_X and LAYOUT_Y, respectively.  This restriction has been removed from the forecast model.
  (2) The check on BLOCKSIZE, i.e. whether the quantity (NX/LAYOUT_X)*(NY/LAYOUT_Y) is evenly divisible by BLOCKSIZE.  This already depends on restriction (1) being satisfied, so it cannot be satisfied if (1) is not satisfied.
  (3) The check on whether NY is evenly divisible by the number of write-component tasks per write-component group.  Tests were run with parameters that violated this test, and the model did not crash, so we assume this is no longer a restriction.
* Modify NCL plotting scripts to make them work with the latest version of the workflow.

### Bug fixes:
* Fix bug in set_predef_grid_params.sh involving an extra space after the equal sign in the lines that set GRID_GEN_METHOD.
* Remove the FV3_RRFS_v1alpha suite from the list of WE2E tests because that suite is not (yet?) supported by the version of ufs-weather-model this PR is using.
* Fix bug in run_experiment.sh where the variable FV3GFS_FILE_FMT_ICS should be replaced with FV3GFS_FILE_FMT_LBCS.

### Improvements:
* Forecast model executable:
  (1) Remove section of code that copies the FV3 executable from its location in the ufs-weather-model directory to the bin directory for all other executables.  This is no longer necessary since the new build system already places this executable in the bin directory.
  (2) Change the name of the forecast model executable to the latest one that is being used in ufs-weather-model.
* Remove commented-out code that was previously used to create module files for the various workflow tasks.
* Change the default physics suite to GFS_v15p2 to be consistent with the release/public-v1 branch.
* Alphabetize namelist variable entries in FV3.input.yml and input.nml.FV3.
* Edit comments.

## TESTS CONDUCTED:
Ran all 49 WE2E tests on Hera.  All except 5 tests succeeded.  The results are as follows:
```
  (1) DOT_OR_USCORE                                                    SUCCESS
  (2) GST_release_public_v1                                            SUCCESS
  (3) community_ensemble_008mems                                       SUCCESS
  (4) community_ensemble_2mems                                         SUCCESS
  (5) get_extrn_files_from_hpss_FV3GFS_FV3GFS                          SUCCESS
  (6) get_extrn_files_from_hpss_GSMGFS_GSMGFS                          SUCCESS
  (7) get_extrn_files_from_hpss_HRRR_RAP                               SUCCESS
  (8) get_extrn_files_from_hpss_RAP_RAP                                SUCCESS
  (9) grid_CONUS_25km_GFDLgrid_FV3GFS_FV3GFS                           SUCCESS
 (10) grid_CONUS_3km_GFDLgrid_FV3GFS_FV3GFS                            SUCCESS
 (11) grid_GSD_HRRR_AK_50km                                            SUCCESS
 (12) grid_GSD_RAP13km                                                 FAILURE
 (13) grid_RRFS_AK_13km_FV3GFS_FV3GFS                                  SUCCESS
 (14) grid_RRFS_AK_13km_RAP_RAP                                        FAILURE
 (15) grid_RRFS_AK_3km_FV3GFS_FV3GFS                                   SUCCESS
 (16) grid_RRFS_AK_3km_RAP_RAP                                         FAILURE
 (17) grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2      SUCCESS
 (18) grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16beta    SUCCESS
 (19) grid_RRFS_CONUS_13km_ics_HRRR_lbcs_RAP_suite_GSD_SAR             SUCCESS
 (20) grid_RRFS_CONUS_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta         SUCCESS
 (21) grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2      SUCCESS
 (22) grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16beta    SUCCESS
 (23) grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_GSD_SAR             SUCCESS
 (24) grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta         SUCCESS
 (25) grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2       SUCCESS
 (26) grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16beta     SUCCESS
 (27) grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_GSD_SAR              SUCCESS
 (28) grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta          SUCCESS
 (29) grid_RRFS_SUBCONUS_3km_FV3GFS_FV3GFS                             SUCCESS
 (30) grid_RRFS_SUBCONUS_3km_HRRR_RAP                                  FAILURE
 (31) nco_CONUS_25km_GFDLgrid                                          SUCCESS
 (32) nco_RRFS_CONUS_25km_HRRR_RAP                                     SUCCESS
 (33) nco_RRFS_CONUS_3km_FV3GFS_FV3GFS                                 SUCCESS
 (34) nco_RRFS_CONUS_3km_HRRR_RAP                                      SUCCESS
 (35) nco_RRFS_SUBCONUS_3km_HRRR_RAP                                   SUCCESS
 (36) nco_ensemble                                                     SUCCESS
 (37) new_ESGgrid                                                      SUCCESS
 (38) new_GFDLgrid                                                     SUCCESS
 (39) new_GFDLgrid__GFDLgrid_USE_GFDLgrid_RES_IN_FILENAMES_eq_FALSE    SUCCESS
 (40) new_GFDLgrid__GFDLgrid_USE_GFDLgrid_RES_IN_FILENAMES_eq_TRUE     SUCCESS
 (41) pregen_grid_orog_sfc_climo                                       SUCCESS
 (42) regional_001                                                     SUCCESS
 (43) regional_002                                                     SUCCESS
 (44) suite_FV3_CPT_v0                                                 FAILURE
 (45) suite_FV3_GFS_v15p2                                              SUCCESS
 (46) suite_FV3_GFS_v16beta                                            SUCCESS
 (47) suite_FV3_GSD_SAR                                                SUCCESS
 (48) suite_FV3_GSD_v0                                                 SUCCESS
 (49) suite_FV3_RRFS_v1beta                                            SUCCESS
```
The 5 failed tests (with information on the failures) are as follows:
```
 (12) grid_GSD_RAP13km
      Failed in most of the run_post tasks.
 (14) grid_RRFS_AK_13km_RAP_RAP
      Failed in the run_fcst task with "AVOST IN VILKA" messages.
 (16) grid_RRFS_AK_3km_RAP_RAP
      Failed in the run_fcst task with "AVOST IN VILKA" messages.
 (30) grid_RRFS_SUBCONUS_3km_HRRR_RAP
      Failed in the run_fcst task without a clear failure message.
 (44) suite_FV3_CPT_v0
      Failed in the run_fcst task with the following namelist read error:
      forrtl: severe (19): invalid reference to variable in NAMELIST input, unit -5, file Internal Formatted NML Read, line -1, position 13
```
Except for FV3_CPT_v0, the failed tests do not use the new RRFS_CONUS grids.  Thus, these failures are not related to the CONUS grid modifications.  The failure of FV3_CPT_v0 is likely due to a bad namelist variable specification and thus also unrelated to the CONUS grid modifications.

Note that all tests using grids for which NX and NY are not evenly divisible by LAYOUT_X and LAYOUT_Y, respectively (which include all 3 new versions of the RRFS_CONUS grids), and thus the quantity (NX/LAYOUT_X)*(NY/LAYOUT_Y) is not evenly divisible by BLOCKSIZE gave warnings of this kind in the log file for the run_fcst task:
`WARNING from PE   478: atmos_modeldefine_blocks_packed: domain (  59  65) is not an even divisor with definition (  32) - blocks will not be uniform with a remainder of   27
`
This warning should either be removed (since this restriction on BLOCKSIZE has been removed from the code) or, if having this remainder makes the model run less efficiently, be replaced by a different caution message.

### CODE REVIEW

**Comment by JeffBeck-NOAA** [comment]
@gsketefian What date did you run for the WE2E cases?

**Comment by JeffBeck-NOAA** [comment]
@gsketefian I will test this on Jet, using a new severe storm case (2020041212).

**Comment by gsketefian** [comment]
@JeffBeck-NOAA The date was 2020080100.  I reran on the 3km grid with the original grid parameters (which satisfy the old constraints on nx, ny, and blockszie), and it was successful.  See my update of the PR message above.

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, unfortunately there are multiple potential sources of failure here.  I'm suspicious that this is related to the RRFS_v1beta SDF and not the nx/y, layout_x/y values.  It is possible that it's the grid, but note that all the cases that use FV3GFS data succeeded with the new grid.  That's the same behavior that @jwolff-ncar has found for the GST date.  I will try the new domains with the new severe storm case that I'm testing (which worked for RAPX/HRRRX data with the RRFS_v1beta SDF).

**Comment by JeffBeck-NOAA** [comment]
After testing the new 3-km domain with HRRRX/RAPX data and with the RRFS_v1beta SDF, I'm now getting instabilities (see below) and the run crashes nearly immediately.  So @gsketefian, I think you may be correct that there are still some domain requirements that have to be met, and we can't use just any NX/NY and LAYOUT_X/Y for now.   This is unfortunate, but I don't know that we can continue given this finding.  We'll need to coordinate with Chan-Hoo and Gerhard to let them know about these findings.  

Given this info, do you feel like you can just tweak the previous 13-km and 25-km domains to include the full CONUS?  We can just go with that for the release.  (The previous 3-km domain contained the full CONUS, correct?)

WARNING, negative qv   -0.1088244E-03 at i,j,k=       3       1       1
WARNING, negative qv   -0.4595275E-03 at i,j,k=      29       1       1
WARNING, negative qv   -0.2130150E-03 at i,j,k=      24       1       1
WARNING, negative qv   -0.1551313E-03 at i,j,k=      19       1       1
WARNING, negative qv   -0.2207158E-02 at i,j,k=      23       1       1
WARNING, negative qv   -0.2189064E-02 at i,j,k=      17       1       1
WARNING, negative qv   -0.2121706E-02 at i,j,k=      11       1       1
WARNING, negative qv   -0.2253924E-02 at i,j,k=      12       1       1
 PASS: fcstRUN phase 1, na =            0  time is    2.72241806983948
 in fcst run phase 2, na=           0
 warning: too much snow :  0.202187500000000
 fix: decrease snow depth to:  0.200000000000000
 warning: too much snow :  0.269156250000000
 warning: too much snow :  0.252187500000000
 warning: too much snow :  0.234281250000000
 fix: decrease snow depth to:  0.200000000000000
 fix: decrease snow depth to:  0.200000000000000

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, I tested this on Jet today (3-km, 13-km, and 25-km domains) and it works with the FV3_GFS_v15p2 SDF.  I can't test the RRFS_v1alpha suite yet, since it's not available in the ufs-weather-model repo.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
