### PR TITLE
Enhancements to Python plotting scripts

### PR DESCRIPTION
**Pull request by BenjaminBlake-NOAA**
## DESCRIPTION OF CHANGES: 
Output files generated by plot_allvars and plot_allvars_diff are now written out to the expt_dir rather than the Python directory under regional_workflow/ush/Python.  In addition, logic has been added to generate plots for a defined set of forecast hours.  The user must now specify the starting/ending forecast hours as well as the forecast hour increment.

## TESTS CONDUCTED: 
These changes were tested on both Hera and Jet.

## ISSUE (optional): 
Resolves issue #376 : https://github.com/NOAA-EMC/regional_workflow/issues/376

## CONTRIBUTORS (optional): 
Ben Blake, David Wright

### CODE REVIEW

**Comment by jwolff-ncar** [comment]
@BenjaminBlake-NOAA When I run the following it is killed when creating the sfc cape/cin plot for hour 7. 

python plot_allvars_diff.py 2019061518 006 009 1 /scratch2/BMC/det/jwolff/GST/expt_dirs/test_gst_CONUS_3km_GFSv15p2 /scratch2/BMC/det/jwolff/GST/expt_dirs/test_gst_CONUS_3km_RRFSv1alpha /scratch2/NCEPDEV/fv3-cam/Chan-hoo.Jeon/tools/NaturalEarth

**Comment by BenjaminBlake-NOAA** [comment]
@jwolff-ncar  What was the error message that it gave?  I looked in your /scratch2/BMC/det/jwolff/GST/expt_dirs/test_gst_CONUS_3km_GFSv15p2 on Hera, and I see that some of the forecast hour 7 plots are missing.

**Comment by jwolff-ncar** [comment]
@BenjaminBlake-NOAA No error message, just gets killed:
...
Working on surface-based CAPE/CIN for conus
Killed

I tried to run hours 8-9 and I had similar behavior and it was killed while running fcst hours 9. Maybe a memory issue?

**Comment by jwolff-ncar** [comment]
Oops - had a nastygram in my email:

Hello,

The following applications were found running under your account on a Hera login node and were identified because they were utilizing a high level of CPU or are included in the list of forbidden processes:

Jamie.W+   6380  107  0.5 76649592 1096632 pts/11 Sl+ 14:14  11:58 python plot_allvars_diff.py 2019061518 006 009 1 /scratch2/BMC/det/jwolff/GST/expt_dirs/test_gst_CONUS_3km_GFSv15p2 /scratch2/BMC/det/jwolff/GST/expt_dirs/test_gst
Jamie.W+  22545  276  1.2 44425904 2452692 pts/11 Rl+ 14:22   8:31 python plot_allvars_diff.py 2019061518 006 009 1 /scratch2/BMC/det/jwolff/GST/expt_dirs/test_gst_CONUS_3km_GFSv15p2 /scratch2/BMC/det/jwolff/GST/expt_dirs/test_gst
Jamie.W+ 139932  136  1.3 8617604 2643528 pts/11 Sl+ 14:16  12:47 python plot_allvars_diff.py 2019061518 006 009 1 /scratch2/BMC/det/jwolff/GST/expt_dirs/test_gst_CONUS_3km_GFSv15p2 /scratch2/BMC/det/jwolff/GST/expt_dirs/test_gst_

The login (front end) nodes are a part of the service nodes and provide access to the rest of the cluster. They are intended for code and batch job management tasks, not for computation.

How are you running this, @BenjaminBlake-NOAA?

**Comment by BenjaminBlake-NOAA** [comment]
Hmm that does sound like a memory issue.  Maybe when running multiple forecast hours we'll need to run it as a batch job and increase the memory limit.  That should resolve the issue.  Would that be a valid solution?  

I tested it on the login node too but admittedly I only tested one forecast hour, and should have tested more than one.  I made sure the start/end/increment logic was working properly though.  @dmwright526 Did you by chance test the script with multiple forecast hours?

**Comment by jwolff-ncar** [comment]
I think running as a batch job is necessary. Hopefully that resolves the issue. I was thinking that since we have to make a batch job we could add it as a task to the workflow. This would be simple for the stand-alone plots but it is much harder for the difference plots given you would have to provide a separate working directory for the comparison. If we want to think about pursuing this we could make it a separate issue. I think we should merge this as is but provide a sample batch script for submission.

**Comment by BenjaminBlake-NOAA** [comment]
That's a good idea!  If users want to run it as part of the workflow, then they would have the option to do so.  Based on that email you got, I'm pretty sure running it as a batch job should fix it.

I'm also on board with your proposal for merging these changes.  I'm mostly familiar with LSF batch submission (which is what WCOSS uses), so it might make more sense for someone else to set up a sample batch script which will work on Hera/Jet.  But I can also get that added to my branch in a day or two if no one else is able to do it.

**Comment by dmwright526** [comment]
@BenjaminBlake-NOAA @jwolff-ncar So I was running on the login nodes of Jet for my testing, and it was taking a bit longer than I would have liked... I did testing for a 10 hour chunk of forecasts (f010 - f019) and it was able to run. Since it was taking so long to run I was worried that it would be booted... Like Ben said, a batch job will probably get around the error. Merging it into the post processing section of the workflow probably wouldn't be too hard to do.

**Comment by JeffBeck-NOAA** [comment]
Hi @jwolff-ncar, @BenjaminBlake-NOAA, and @dmwright526.  Just catching up on all this now.  I think the change that allowed for a range of forecast hours to be processed now trips the NOAA sys admins' front-end node load monitoring scripts.  I'd agree that submitting a simple batch script to queue is the best solution.  I think I'd actually vote against adding it directly to the workflow, since this isn't a task that's considered fundamental to the end-to-end system (and wouldn't be run in operations).  Would everyone be OK with just having the user manually submit it to queue on the command line?  We could have two scripts (one for the basic plots and another for the difference plots) and the user can decide which is appropriate for their needs.

**Comment by JeffBeck-NOAA** [comment]
@jwolff-ncar, @BenjaminBlake-NOAA @dmwright526, On second thought, we have the capability to turn off certain tasks in the workflow when generating a experiment configuration, so we could add both the basic and difference plots as separate tasks, then provide a config.sh option to shut them off.  Then the user can what they want at workflow generation time.  I'd also do this for the verification step.  We currently have this on/off option for the grid, orog, and topo filtering tasks.  Tagging @gsketefian, as he implemented this functionality.

**Comment by jwolff-ncar** [comment]
Yes, this should be added with the option to turn it on/off. All verification tasks are also implemented that way. It can be set to false by default. I think it would be nice to add the plotting for a single run in the workflow. I think the differencing may have to be a stand-alone batch script though because both directories would need to be available and it could get confusing to add that into the workflow. So, it may be a hybrid approach.

**Comment by BenjaminBlake-NOAA** [comment]
@JeffBeck-NOAA  @jwolff-ncar  I think what Jamie is proposing makes sense!  Incorporate the non-difference plots into the workflow with the option to turn them on or off, and then have the differencing plot capability outside of the workflow.

**Comment by jwolff-ncar** [comment]
I put an example batch script together on hera (/scratch2/BMC/det/jwolff/GST/ufs-srweather-app-gst/regional_workflow/ush/Python/sq_job.sh) copying what is used under (/scratch2/BMC/det/jwolff/GST/ufs-srweather-app-gst/regional_workflow/ush/wrappers)
but I am getting the following error:
--- Logging error ---
Traceback (most recent call last):
  File "/contrib/anaconda/anaconda3/latest/lib/python3.7/logging/handlers.py", line 939, in emit
    self.socket.sendto(msg, self.address)
OSError: [Errno 101] Network is unreachable
@JulieSchramm or @llpcarson  do you have a suggestion on this given I used the stand-alone wrapper as a starting point?

**Comment by JulieSchramm** [comment]
Can you try putting this in your script (for hera):

module use -a /contrib/miniconda3/modulefiles
module load miniconda3
conda activate regional_workflow

**Comment by JeffBeck-NOAA** [comment]
> @JeffBeck-NOAA @jwolff-ncar I think what Jamie is proposing makes sense! Incorporate the non-difference plots into the workflow with the option to turn them on or off, and then have the differencing plot capability outside of the workflow.

Yep, definitely agree this is the way to go.

**Comment by jwolff-ncar** [comment]
Thanks for the suggestion, @JulieSchramm , but that didn't seem to work for me.

**Comment by dmwright526** [comment]
@jwolff-ncar I don't think the regional_workflow environment has the plotting tools needed for the python scripts, specifically cartopy. Try:
conda activate adb_graphics

You can also do "conda env list" to see other environment options on Hera.

**Comment by jwolff-ncar** [comment]
Thanks for the suggestion, @dmwright526. I tried adding that to the batch script but that also did not do the trick. (We need to get  It is something in the way the environment is set in the batch script. I am not familiar with fixing this so hopefully we will get other suggestions on how to get this working.

You can see the script here:
/scratch2/BMC/det/jwolff/GST/ufs-srweather-app-gst/regional_workflow/ush/Python/sq_job.sh

Submitted with:
sbatch sq_job.sh

**Comment by jwolff-ncar** [comment]
If anyone has any other ideas on how to get the batch script to work (setting the environment correctly) please let me know! I have been unsuccessful.

**Comment by BenjaminBlake-NOAA** [comment]
@jwolff-ncar  I will take a look next week and see if I can figure anything out, though I'm probably not be the best person to do this.  Happy new year!

**Comment by dmwright526** [comment]
@jwolff-ncar @BenjaminBlake-NOAA I will try to take a look at the submission script later this morning. It has been a while since I have done anything on Hera, but I will give it a try!

**Comment by dmwright526** [comment]
@jwolff-ncar I think I may have figured out part of the problem... You are loading miniconda3 and then loading Anaconda afterwards. Just loading miniconda3 should fix things (remove lines 44 through 47).

This does bring up another problem in that I don't see the library for netCDF4 on Hera right now in the adb_graphics environment (it is here on Jet) or the regional_workflow environment. Have you run the plotting script before on Hera without a batch script?

**Comment by jwolff-ncar** [comment]
Interesting, I tried running without those lines and now I get this error:
ModuleNotFoundError: No module named 'netCDF4'
Must be a change on the system...

**Comment by dmwright526** [comment]
That is the same error I am getting now. The extra lines you had in the script was loading Anaconda on top of Miniconda, which I think was pointing things to the wrong version of python (purely a guess). The lack of the netCDF4 module appears to be a separate issue...

**Comment by BenjaminBlake-NOAA** [comment]
@jwolff-ncar @dmwright526  Sorry I haven't had a chance to look at this yet.  But that is odd about the netCDF4 module missing and I do not recall getting that error when I ran the plotting job on Hera without the batch script.  However, I also used a different version of anaconda:
module use /contrib/anaconda/modulefiles
module load anaconda/latest
I probably should have used the version defined within the workflow.

**Comment by dmwright526** [comment]
@BenjaminBlake-NOAA @jwolff-ncar Ah, I see what is happening now! The batch script will work if you are using Anaconda:
module use /contrib/anaconda/modulefiles
module load anaconda/latest

It currently will not work with miniconda3 on Hera due to the lack of netCDF4 module installed in the Miniconda3 environments. @jwolff-ncar your issue came from trying to load both Anaconda and Miniconda3, resulting in wires getting crossed somewhere... Your script will run if you use Anaconda (at least it looks like it is working on my end).

This discussion I think points more to the problem that we do not have the plotting modules available in the regional_workflow environments on the machines.

**Comment by JeffBeck-NOAA** [comment]
> @BenjaminBlake-NOAA @jwolff-ncar Ah, I see what is happening now! The batch script will work if you are using Anaconda:
> module use /contrib/anaconda/modulefiles
> module load anaconda/latest
> 
> It currently will not work with miniconda3 on Hera due to the lack of netCDF4 module installed in the Miniconda3 environments. @jwolff-ncar your issue came from trying to load both Anaconda and Miniconda3, resulting in wires getting crossed somewhere... Your script will run if you use Anaconda (at least it looks like it is working on my end).
> 
> This discussion I think points more to the problem that we do not have the plotting modules available in the regional_workflow environments on the machines.

Thanks @dmwright526 for finding the problem!  @jwolff-ncar, please let us know whether that works for you.  If it does, then we'll need to coordinate with @christinaholtNOAA to get the required plotting modules added to the conda regional_workflow environments on each platform.  @dmwright526, can you provide a list of which ones need to be added?  Thanks!

**Comment by dmwright526** [comment]
@JeffBeck-NOAA The list below is based on what works on Jet using the environment adb_graphics. The versions listed are not set in stone, but at least gives a starting point. The version of python _could_ be a problem as regional_workflow is using 3.8.0 and adb_graphics is using 3.8.2, but I wouldn't bet on it. I didn't list any dependent libraries, but those should be automatically installed when these are installed.

- pygrib  v2.0.4
- cartopy  v0.17.0
- matplotlib  v3.2.1
- python-dateutil  v2.8.1
- pillow  v7.1.1
- numpy  v1.18.1
- scipy  v1.4.1
- pyproj  v2.6.0

@BenjaminBlake-NOAA it turns out that we don't use the netCDF4 module in the scripts (I don't know if I snuck it in there accidentally during testing or if it was carryover from a legacy version of the script). Would you be able to remove it in this PR? If I am missing where it is being used, let me know.

**Comment by christinaholtNOAA** [comment]
I can just mention that the pygraf conda environment is a newer version of the adb_graphics environment and does include netCDF4 for those who need both. Get it by activating pygraf like this:

```
module use -a /contrib/miniconda3/modulefiles
module load miniconda3
conda activate pygraf
```

**Comment by BenjaminBlake-NOAA** [comment]
@dmwright526 Yep, it looks like the netCDF4 module is not needed!  I think it is left over from a legacy version of the script.  I'll remove it now.  I'll try and edit the files directly on Github, I think I did that once before

**Comment by jwolff-ncar** [comment]
I still cannot get the batch script to run. When I run 'sbatch sq_job.sh' under /scratch2/BMC/det/jwolff/GST/ufs-srweather-app-gst/regional_workflow/ush/Python, I get:
--- Logging error ---
Traceback (most recent call last):
  File "/contrib/anaconda/anaconda3/latest/lib/python3.7/logging/handlers.py", line 939, in emit
    self.socket.sendto(msg, self.address)
OSError: [Errno 101] Network is unreachable

@dmwright526 Can you point me to the batch script you are submitting on hera? Or if anyone else has a successful script on hera, please let me know.

**Comment by dmwright526** [comment]
Thanks for the information on pygraf @christinaholtNOAA and thanks for adjusting the script @BenjaminBlake-NOAA !

@jwolff-ncar you can find my job script here:
/scratch2/BMC/wrfruc/David.M.Wright/sq_job.sh

I adjusted it back to be pointing to your data, but you will need to adjust the submission account and working directory. If that doesn't work, let me know.

**Comment by jwolff-ncar** [comment]
Thanks for the path to your script. I do not know why it works for you and not me. I diffed them and there is nothing that should be causing an issue. I still get:
Traceback (most recent call last):
  File "/contrib/anaconda/anaconda3/latest/lib/python3.7/logging/handlers.py", line 939, in emit
    self.socket.sendto(msg, self.address)
OSError: [Errno 101] Network is unreachable

@BenjaminBlake-NOAA or @JeffBeck-NOAA Do you want to try to run it once? If two people can run it on hera we will assume the script is good and it is simply a problem with my environment.

**Comment by christinaholtNOAA** [comment]
@jwolff-ncar I have seen some issues like that early on with my miniconda installation. It could be something related to the internals fo the Anaconda installation. 

Are you willing to try with the miniconda3 module and the pygraf environment to see if that will work? You shouldn't see any paths to anaconda if you have that loaded.

**Comment by jwolff-ncar** [comment]
Thank you, @christinaholtNOAA. Using:
module use -a /contrib/miniconda3/modulefiles
module load miniconda3
conda activate pygraf
seems to be working!

**Comment by JeffBeck-NOAA** [comment]
> Thank you, @christinaholtNOAA. Using:
> module use -a /contrib/miniconda3/modulefiles
> module load miniconda3
> conda activate pygraf
> seems to be working!

@jwolff-ncar, are we good to merge this PR?

**Comment by jwolff-ncar** [comment]
I think it can be merged. We will want to add some sample submission scripts but that can be done in a different PR.

**Comment by JeffBeck-NOAA** [comment]
@jwolff-ncar, OK, thanks!  I'll approve now.  @BenjaminBlake-NOAA, feel free to merge!

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by jwolff-ncar** [comment]
@BenjaminBlake-NOAA We will need to get these updates into the release branch as well. Is that something you have time to do? Thanks!

**Comment by BenjaminBlake-NOAA** [comment]
@jwolff-ncar  Sure!  I can submit a PR for that tomorrow morning, does that sound good?

**Comment by jwolff-ncar** [comment]
@BenjaminBlake-NOAA That sounds great! Thank you!

**Pull request merged**
