### PR TITLE
Add echo top verification and interpolation options for different fields [into develop]

### PR DESCRIPTION
**Pull request by jwolff-ncar**
## DESCRIPTION OF CHANGES: 
- Added capability to pull MRMS echo top data from the the NOAA HPSS and run echo top verification through grid-stat
- Updated point-stat conf files to allow for ceiling, visibility, and total cloud to use nearest neighbor interpolation while the rest of the fields use bilinear interpolation
- Changed maxtries for post task to be 2 since it fails on occasion but typically runs fine if reissued.

## TESTS CONDUCTED: 
Ran the GST test

Ran a test including the verification steps on hera using the following settings in my config.sh

PREDEF_GRID_NAME="RRFS_CONUS_25km"
QUILTING="TRUE"

CCPP_PHYS_SUITE="FV3_GFS_v15p2"
FCST_LEN_HRS="48"
LBC_SPEC_INTVL_HRS="6"

DATE_FIRST_CYCL="20200415"
DATE_LAST_CYCL="20200415"
CYCL_HRS=( "00" )

EXTRN_MDL_NAME_ICS="FV3GFS"
EXTRN_MDL_NAME_LBCS="FV3GFS"

FV3GFS_FILE_FMT_ICS="grib2"
FV3GFS_FILE_FMT_LBCS="grib2"

WTIME_RUN_FCST="01:00:00"

MODEL="FV3_GFS_v15p2_CONUS_25km"
METPLUS_PATH="/scratch1/BMC/dtc/George.Mccabe/METplus.bugfix_914"
MET_INSTALL_DIR="/contrib/met/9.0.2"
CCPA_OBS_DIR="/scratch2/BMC/fv3lam/jwolff/obs_data/ccpa/proc"
MRMS_OBS_DIR="/scratch2/BMC/fv3lam/jwolff/obs_data/mrms/proc"
NDAS_OBS_DIR="/scratch2/BMC/fv3lam/jwolff/obs_data/ndas/proc"

RUN_TASK_MAKE_GRID="TRUE"
RUN_TASK_MAKE_OROG="TRUE"
RUN_TASK_MAKE_SFC_CLIMO="TRUE"
RUN_TASK_GET_OBS_CCPA="TRUE"
RUN_TASK_GET_OBS_MRMS="TRUE"
RUN_TASK_GET_OBS_NDAS="TRUE"
RUN_TASK_VX_GRIDSTAT="TRUE"
RUN_TASK_VX_POINTSTAT="TRUE"

### CODE REVIEW

**Comment by mkavulich** [comment]
@jwolff-ncar Can you clarify in what contexts you're seeing post jobs fail inconsistently? I haven't encountered that.

**Comment by jwolff-ncar** [comment]
@mkavulich When I run a test in the cron I more times than not have a post task that fails. As soon as it is kicked off again it usually finishes no problem. I have heard of others trying 3-4 times but I usually only need to try twice.

**Comment by PerryShafran-NOAA** [comment]
I had an error in the execution of run_fcst that looked like this:

  '\''nsout'\'': -1' -t /scratch2/NCEPDEV/fv3-cam/Perry.Shafran/ufs-srweather-app/regional_workflow/ush/templates/model_configure -o /scratch2/NCEPDEV/fv3-cam/Perry.Shafran/expt_dirs/test_community/2020041500/model_configure
slurmstepd: error: execve(): /scratch2/NCEPDEV/fv3-cam/Perry.Shafran/ufs-srweather-app/bin/ufs_model: No such file or directory

In order to build the regional workflow, I had to build the whole ufs-srweather-app workflow using the most recent version of the Get started instructions.  But there is no file called ufs_model in the bin directory.  Is there something wrong I did in the build?  

Perry

**Comment by PerryShafran-NOAA** [comment]
I found the issue.  Looks line in the config.defaults.sh, there was a line set incorrectly:

FV3_EXEC_FN="ufs_model"

should be

FV3_EXEC_FN="NEMS.exe"

Perry

**Comment by PerryShafran-NOAA** [comment]
Well, now I got a real crash and don't know how to diagnose this one.  Can someone look at it?  

WARNING from PE     5: atmos_modeldefine_blocks_packed: domain (  41  58) is not an even divisor with definition (  40) - blocks will not be uniform with a re
mainder of   18


WARNING from PE     0: atmos_modeldefine_blocks_packed: domain (  41  58) is not an even divisor with definition (  40) - blocks will not be uniform with a re
mainder of   18


WARNING from PE     0: atmos_modeldefine_blocks_packed: domain (  41  58) is not an even divisor with definition (  40) - blocks will not be uniform with a re
mainder of   18


WARNING from PE     4: atmos_modeldefine_blocks_packed: domain (  41  58) is not an even divisor with definition (  40) - blocks will not be uniform with a re
mainder of   18


WARNING from PE     9: atmos_modeldefine_blocks_packed: domain (  41  58) is not an even divisor with definition (  40) - blocks will not be uniform with a re
mainder of   18

forrtl: severe (19): invalid reference to variable in NAMELIST input, unit -5, file Internal Formatted NML Read, line -1, position 15
Image              PC                Routine            Line        Source
NEMS.exe           0000000002EE4662  Unknown               Unknown  Unknown
NEMS.exe           0000000002F1905F  Unknown               Unknown  Unknown
NEMS.exe           0000000002F16F8B  Unknown               Unknown  Unknown
NEMS.exe           000000000252D8C7  Unknown               Unknown  Unknown
NEMS.exe           0000000002448DD3  Unknown               Unknown  Unknown
NEMS.exe           000000000230D7A5  Unknown               Unknown  Unknown
NEMS.exe           00000000019B0966  Unknown               Unknown  Unknown
NEMS.exe           0000000001975D76  Unknown               Unknown  Unknown
NEMS.exe           000000000078AF01  _ZN5ESMCI6FTable1        2010  ESMCI_FTable.C
NEMS.exe           000000000078EAE6  ESMCI_FTableCallE         746  ESMCI_FTable.C
NEMS.exe           0000000000A9480A  _ZN5ESMCI2VM5ente        1178  ESMCI_VM.C
NEMS.exe           000000000078C537  c_esmc_ftablecall         898  ESMCI_FTable.C

See /scratch2/NCEPDEV/fv3-cam/Perry.Shafran/expt_dirs/test_community/log/run_fcst_2020041500.log

Perry

**Comment by PerryShafran-NOAA** [comment]
@michelleharrold  Ooh, I might have done that, as that is what is listed in the instructions on the Get Started page.  I'll try your clone and see what happens.  Thanks!

**Comment by michelleharrold** [comment]
I was unable to produce echo top output -- I noticed in the templates/FV3LAM_wflow.xml that RETOP is added to the GET_OBS_MRMS task (and pulls successfully when I run), but it doesn't appear anywhere else in the xml. It likely either needs to have a new task added or be added to be run in the VX_GRIDSTAT_REFC task.

**Comment by jwolff-ncar** [comment]
Ha - Minor detail!
For clarity and ease of turning it off/on, I think it should be added as a new task. Let me know if you disagree. I will do that soon and retest. 
Thanks @michelleharrold

**Comment by PerryShafran-NOAA** [comment]
@michelleharrold There are several types of reflectivity verification that we run, and the REFC alone does not do verification for RETOP.  It's probably not a bad idea to have it as its own job, just like the various precip verification jobs are in different tasks by accumulation length.  I would recommend a new job as well.

**Comment by PerryShafran-NOAA** [comment]
One more thing that I noticed, and this is probably pretty minor, is that the filenames in postprd seem to have an added "00" to the forecast hour:

rrfs.t00z.bgdawpf03600.tm00.grib2

instead of

rrfs.t00.bgdawpf036.tm00.grib2

Where did the extra 00 come from?  I would have to change the METplus config files to accommodate.

**Comment by JeffBeck-NOAA** [comment]
@PerryShafran-NOAA, you probably have the version of the code that can produce sub-hourly output, but didn't have the fix in place to correctly output post files when only running hourly.  Are you running with the HEAD of regional_workflow?

**Comment by PerryShafran-NOAA** [comment]
I am running as @michelleharrold had suggested, by doing a git clone on the repository, then another git clone on Jamie's version of the regional workflow.  But you are saying that there is a fix that isn't included in Jamie's feature branch?  Is there something I need to do to ensure that I get this fix?

**Comment by JeffBeck-NOAA** [comment]
@PerryShafran-NOAA, my guess is that @jwolff-ncar needs to issue a "git pull upstream develop" command in her fork to get the latest develop branch commits merged into her branch.

**Comment by jwolff-ncar** [comment]
I have synced this feature branch with develop since the sub-hourly fixes went in. The verification task does not run without that as you have probably noticed, @PerryShafran-NOAA. Why don't you send me an email with the steps you have used and we can take that part offline?

**Comment by PerryShafran-NOAA** [comment]
I just completed a successful end-to-end run of the workflow on Hera, including with the addition of the RETOP verification added by @jwolff-ncar.  I will attempt an end-to-end run on WCOSS now and see how well that works.

**Comment by PerryShafran-NOAA** [comment]
I guess I won't be able to test fully on WCOSS since this version of METplus is not likely to be there. But perhaps the best way to test this there is to use METplus v 4.0.0 and MET v 10.0.0, which are newly installed on WCOSS (and Hera) and should have the fix in there.  In fact it might not be a bad idea to do the PR using an official installation of METplus to be sure it can be used on other platforms.  

METPLUS_PATH="/scratch1/BMC/dtc/George.Mccabe/METplus.bugfix_914"

**Comment by jwolff-ncar** [comment]
Yes, @PerryShafran-NOAA please do go ahead and test this with the latest release. It should have the fix.  The METplus path in the config.sh will not part of the commit so it is ok to proceed as is but please let me know how your test on WCOSS goes. Thanks!

**Comment by jwolff-ncar** [comment]
My latest test with the updated PR on hera ran to completion and had RETOP vx output. Thank you to Michelle for noticing that oversight. Let me know if you see any other problems @PerryShafran-NOAA @LoganDawson-NOAA @michelleharrold

**Comment by PerryShafran-NOAA** [comment]
End-to-end system was successfully run on Hera, including RETOP output, using the /contrib versions of MET v 10.0.0 and METplus 4.0.0 rather than George McCabe's bugfix version.  I will attempt to run this on WCOSS using MET v 10.0.0 and METplus 4.0.0 as well.

One thing that had to be changed was the MET config files in ../ufs-srweather-app/regional_workflow/ush/templates/parm/met needed to all be modified because they had the version number specified in them.  The line:

version        = "V9.0.2";

needed to be updated to V10.0.0.  Alternatively, MET and METplus still work with this line commented out.  When specified, though, the version number in the MET config files need to be exactly the same as the version you are pointing to in the config.sh file, otherwise verification won't run.  

I updated these files to V10.0.0 and the verification worked fine.

**Review by michelleharrold — APPROVED** [review]
@jwolff-ncar - I re-ran my test on hera with your latest changes, and everything ran as expected.

**Comment by jwolff-ncar** [comment]
@PerryShafran-NOAA Very good point on the MET version number. I will plan to fix this in a future PR through the addition of a namelist variable that can be set in the config.sh.

**Pull request merged**
