### PR TITLE
Post and multi-domain generalization

### PR DESCRIPTION
**Pull request by MatthewPyle-NOAA**
My changes from this week to get rid of the direct "mpirun" kinds of commands for the post, and add the ability to set different resource requirements for non-CONUS domains for model and post jobs.   Fairly well tested at least for the Hawaii FV3SAR domain on theia.  Made some preliminary changes for "first guess" types of jobs, but those were not tested.

### CODE REVIEW

**Comment by MatthewPyle-NOAA** [comment]
Hi Bin,

Thanks for going over it.  Glad to hear some of the changes can be simplified.  I have attempted to put at least some of those changes into my branch (my local copy), but haven't yet tested them and likely won't get a chance by the end of the day.  I'd probably feel more comfortable if you made the changes since you know the details of this workflow better than me.  

-Matt

**Comment by MatthewPyle-NOAA** [comment]
Hi Bin,

I was able to make some post tests, and realized that the site definition files needs modification when eliminating the more unique APRUNC variants.   For example, the various POST_RESOURCES items should define TOTAL_TASKS_POST instead of TOTAL_TASKS

  <!ENTITY POST_RESOURCES_conus "<nodes>2:ppn=24</nodes><envar><name>TOTAL_TASKS_POST</name><value>48</value></envar><envar><name>OMP_THREADS</name><value>1</valu
  <!ENTITY POST_RESOURCES_ak "<nodes>2:ppn=24</nodes><envar><name>TOTAL_TASKS_POST</name><value>48</value></envar><envar><name>OMP_THREADS</name><value>1</value><
  <!ENTITY POST_RESOURCES_hi "<nodes>1:ppn=24</nodes><envar><name>TOTAL_TASKS_POST</name><value>24</value></envar><envar><name>OMP_THREADS</name><value>1</value><
  <!ENTITY POST_RESOURCES_pr "<nodes>1:ppn=24</nodes><envar><name>TOTAL_TASKS_POST</name><value>24</value></envar><envar><name>OMP_THREADS</name><value>1</value><
  <!ENTITY POST_RESOURCES_guam "<nodes>1:ppn=24</nodes><envar><name>TOTAL_TASKS_POST</name><value>24</value></envar><envar><name>OMP_THREADS</name><value>1</value

-Matt

**Comment by MatthewPyle-NOAA** [comment]
I will take a stab at pushing the needed changes to the branch, but they won't be fully tested.

**Comment by BenjaminBlake-NOAA** [comment]
@MatthewPyle-NOAA If you want to push the changes to the branch I can go ahead and test them.  I have forecast output on Theia which I can use.

**Comment by BinLiu-NOAA** [comment]
Hi Matt,

Please go ahead push all your changes into the feature/merge_comm_to_EMC branch. It should be fine since this is not the develop branch. I will work with Ben for further modifications.

Thanks!

Bin

**Pull request merged**
