### PR TITLE
Fix ensemble mode stochastic pattern seed values for ad-hoc and SPP schemes.

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
## DESCRIPTION OF CHANGES: 
This PR fixes the stochastic pattern seed values for SPP, SPPT, SKEB, and SHUM when running in ensemble mode.  Previously, the cycle date that was used to create the seed values was not being correctly updated with the CDATE of each cycle.  Seed values are now set as part of the forecast task instead of being set during either workflow generation or the make_grid task, as was done before.  This PR also reduces the default SPPT magnitude to 0.7 given recent testing showing instabilities with anything larger.

## TESTS CONDUCTED: 
Tested on Jet.

## CONTRIBUTORS (optional): 
@gsketefian and @chunhuazhou

### CODE REVIEW

**Comment by michelleharrold** [comment]
I tested on hera (20200615, 36-h fcst; 10 members; GSD_SAR physics suite at 25km). Members 1-7,10 ran as expected. Seed values were generated appropriately and output looked good. Members 8 and 9 failed when running the forecast due to an issue with generating the unique seed values. The problem lies in: regional_workflow/ush/set_FV3nml_stoch_params.sh on lines 98-101. The error has to do with the leading zero with ensmem_num (bash treats numbers preceded with a zero as an octal and apparently 08 and 09 are out of range for octal). I modified the script to remove the leading zero in ensmem_num and was able to run mem08 and mem09 successfully. As a note, my config.sh: /scratch2/BMC/det/harrold/ufs-srw_seed_retest/expt_dirs/test_ens_seed/config.sh

**Review by michelleharrold — CHANGES_REQUESTED** [review]
I tested on hera (20200615, 36-h fcst; 10 members; GSD_SAR physics suite at 25km). Members 1-7,10 ran as expected. Seed values were generated appropriately and output looked good. Members 8 and 9 failed when running the forecast due to an issue with generating the unique seed values. The problem lies in: regional_workflow/ush/set_FV3nml_stoch_params.sh on lines 98-101. The error has to do with the leading zero with ensmem_num (bash treats numbers preceded with a zero as an octal and apparently 08 and 09 are out of range for octal). I modified the script to remove the leading zero in ensmem_num and was able to run mem08 and mem09 successfully. As a note, my config.sh: /scratch2/BMC/det/harrold/ufs-srw_seed_retest/expt_dirs/test_ens_seed/config.sh

**Comment by JeffBeck-NOAA** [comment]
@michelleharrold, thank you for finding the octal bug!  I have added bash syntax to convert the ensemble member numbers from octal to base 10 prior to computing the seed values.  If you have time, could you please do a "git pull" and retest for the members which were failing for you?  Thanks!

**Review by michelleharrold — APPROVED** [review]
@JeffBeck-NOAA -- I tested the latest mods to account for the issue with octal. The namelist was generated appropriately, and everything ran as expected. Looks good to me!

**Comment by JeffBeck-NOAA** [comment]
> @JeffBeck-NOAA -- I tested the latest mods to account for the issue with octal. The namelist was generated appropriately, and everything ran as expected. Looks good to me!

Thanks, @michelleharrold!

**Pull request merged**
