### PR TITLE
adding scripts for getting nomads data

### PR DESCRIPTION
**Pull request by panll**
new files:
         ush/NOMADS_get_extrn_mdl_files_grib.sh
         ush/NOMADS_get_extrn_mdl_files_nemsio.sh

The codes are for getting data from NOMADS.

They are independent of other codes. No change to other codes.
The codes are tested on Hera.

### CODE REVIEW

**Comment by panll** [comment]
Thanks, Jeff! I'll modified accordingly. @JeffBeck-NOAA

**Comment by panll** [comment]
updated with one file now. @JeffBeck-NOAA

**Comment by mkavulich** [comment]
Is there any documentation on how to stage data once you have downloaded it using this script? Is it meant to be used with Gerard's changes in #246?

**Comment by panll** [comment]
Yes, this code needs to coordinate with Gerard's changes. @mkavulich

**Comment by panll** [comment]
Updated and tested on Hera. The codes passed the test with nemsio data format. The code can download grib2 data successfully and needs to be tested with updated chgres.  Ready to merge. @JeffBeck-NOAA

**Comment by JeffBeck-NOAA** [comment]
@panll Hi Linlin, when you have a chance, would you be able to resolve the conflicts listed?  Thanks!

**Comment by panll** [comment]
Sorry for the late reply! the conflicts are fixed. @JeffBeck-NOAA

**Comment by panll** [comment]
Updated. @JeffBeck-NOAA

**Comment by panll** [comment]
I'll add a WE2E test. Thanks! @gsketefian

**Comment by panll** [comment]
One test for getting online data is added to WE2E. The code is tested on Here. The nemsio data are only available within recent one or two days, and the test cycle needs to be modified accordingly. Thanks! @gsketefian

**Comment by JeffBeck-NOAA** [comment]
(@gsketefian FYI) @panll Thanks for getting this updated!  I just tried running on Jet, but it doesn't look like I can connect to the NOMADS server, either when running the generate script, or when trying to connect to the server directly from the front-end nodes.  Have you ever been able to do that on Jet?  I just tried with Hera, and "wget" works just fine with the NOMADS server there.

Based on a quick survey of the functionality, there are a few additions I'd like to add for the release (bulleted below). @panll, since you're no longer on the UFS-CAM task, and this isn't related to CCPP, I know you have no time to work on this.  I will try to get these changes in myself.  If you and @gsketefian are OK with it, I suggest we merge this PR now, before it becomes out of date again, and I will open a new PR to implement the changes below.  Sound OK?

- Jeff

- Add the option to download HRRR, RAP, or NAM grib2 files:
- - HRRR: https://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.YYYYMMDD/conus/hrrr.tCYz.wrfnatfFH.grib2 
- - RAP: https://nomads.ncep.noaa.gov/pub/data/nccf/com/rap/prod/rap.YYYYMMDD/rap.tCYz.wrfnatfFH.grib2 
- - NAM: https://nomads.ncep.noaa.gov/pub/data/nccf/com/nam/prod/nam.YYYYMMDD/nam.tCYz.bgrd3dFH.tmCY.grib2
- Add a "fcst_model" command line variable to the NOMADS shell script to choose between models, then read in EXTRN_MDL_NAME_ICS and EXTRN_MDL_NAME_LBCS config.sh variables in the generate script call to the NOMADS script.
- Add option to pull different model data for external model ICs vs LBCs
- Add check to fail if model data is not FV3GFS, HRRR, RAP, or NAM
- Only allow nemsio option with FV3GFS data
- Change HRRRX or RAPX external model option to HRRR or RAP, since we can now run with both HRRRX/HRRR and RAPX/RAP data

**Comment by panll** [comment]
fe7:/home/Linlin.Pan>wget https://github.com/ufs-community/ufs-mrweather-app/pull/187
--2020-09-08 17:11:20--  https://github.com/ufs-community/ufs-mrweather-app/pull/187
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘187’

    [ <=>                                   ] 270,418     --.-K/s   in 0.1s    

2020-09-08 17:11:22 (1.73 MB/s) - ‘187’ saved [270418]

**Comment by JeffBeck-NOAA** [comment]
@panll, thanks for checking "wget" on Jet.  Can you try the following?

wget https://nomads.ncep.noaa.gov/pub/data/nccf/com/nam/prod/nam.20200902/nam.t00z.alaskanest.hiresf28.tm00.grib2.idx

That fails for me.  I think there's a firewall issue that is preventing access to the NOMADS server.  Curtis was going to send in a help ticket related to this problem.

I will go ahead and merge this PR so that @fentoad72 can start working on the next steps.

**Comment by panll** [comment]
That website can not see through firefox, safari, or chrome.  Here is the error message:

Not Found
The requested URL /pub/data/nccf/com/nam/prod/nam.20200902/nam.t00z.alaskanest.hiresf28.tm00.grib2.idx was not found on this server.

**Comment by JeffBeck-NOAA** [comment]
@panll, can you try that wget command on Jet?  That's where I was wondering if you could test it.  I wasn't able to connect when I tested there.

**Comment by panll** [comment]
Yes, wget does not work properly on jet for this website:

--2020-09-10 04:07:44--  https://nomads.ncep.noaa.gov/pub/data/nccf/com/nam/prod/nam.20200910/nam.t00z.afwaca84.tm00.grib2.idx
Resolving nomads.ncep.noaa.gov (nomads.ncep.noaa.gov)... 140.172.138.18
Connecting to nomads.ncep.noaa.gov (nomads.ncep.noaa.gov)|140.172.138.18|:443...

I don't know why. @JeffBeck-NOAA

**Comment by fentoad72** [comment]
Created feature_249_nomadsoptions

Added time and date checking for forecast request time (less than 3 days old, multiple of 6)
Added forecast interval checking (multiple of 3)
Added forecast length checking (multiple of 3)

**Pull request merged**
