### PR TITLE
Remove fhcyc=24 references in FV3.input.yml and remove unnecessary FV…

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
…3_GSD_SAR_v1 input.nml file

### CODE REVIEW

**Comment by JeffBeck-NOAA** [comment]
This PR covers issue #223.

**Comment by JeffBeck-NOAA** [comment]
I thought Mike's automatic PR template would prompt me to enter information, but I'm not seeing it.

**Comment by JeffBeck-NOAA** [comment]
@panll @gsketefian Linlin, can you confirm that the stanza for the FV3_GSD_SAR_v1 suite in FV3.input.yml is complete?

**Comment by gsketefian** [comment]
@panll You can try running the WE2E test regional_013 and see if the input.nml file it creates is what you expect.

**Comment by JeffBeck-NOAA** [comment]
@panll Just seeing if Linlin was able to test this commit with the regional_013 WE2E test that Gerard mentioned above?

**Comment by panll** [comment]
i'll test it. @JeffBeck-NOAA

**Comment by JeffBeck-NOAA** [comment]
Thank you, Linlin!

**Comment by panll** [comment]
I tested with FV3.input.yml, the code can run fine for GSD_SAR_v1. One minor issue is that lsoil_lsm is set to 9, normally it is set to 4 for noah lsm. The new repository needs to set sorc and exec directory manually.
@JeffBeck-NOAA

**Comment by panll** [comment]
Tested. @gsketefian

**Pull request closed without merging**
