### PR TITLE
Add stand-alone Python data ingest tool.

### PR DESCRIPTION
**Pull request by christinaholtNOAA**
## DESCRIPTION OF CHANGES: 
This tool is a stand alone script that can be used to grab external model files from a variety of sources including the internet, disk, and HPSS. The known locations for BDP AWS, HPSS, and NOMADS have been added here for demo purposes. It will also accept command line options to support user-defined disk locations with the caveat that file names provided on the command line must match the formatting necessary in the config file. A list of options for data_stores can be provided, and each will be checked until the required files are found. The list of known locations could easily be extended to add observation file locations for verification and data assimilation (future) purposes.

This tool has not yet been hooked into the workflow. I would like to receive feedback on the tool itself before moving forward with replacing existing functionality in the run scripts. 

I envision that this tool would be called from a job script, so am unsure whether it makes sense to store it under ush or scripts.

Example of pulling grib2 files from hpss or aws for FV3GFS:
```
    python retrieve_data.py 
        --anl_or_fcst fcst 
        --cycle_date 2022010212 
        --data_stores hpss aws 
        --external_model FV3GFS 
        --file_type grib2
        --fcst_hrs 0 3 
        --output_path test_output_loc 
        --config ./templates/data_locations.yml 
        --debug 
        --file_type grib2
```
Similarly, if you wanted to check disk first:
```
    files=settings="
        'grib2':
           'fcst': gfs.t{hh}z.pgrb2.0p25.f{fcst_hr:03d}
    "
    python retrieve_data.py 
        --anl_or_fcst fcst 
        --cycle_date 2022010212 
        --data_stores hpss aws 
        --external_model FV3GFS 
        --file_type grib2
        --fcst_hrs 0 3 
        --output_path test_output_loc 
        --config ./templates/data_locations.yml 
        --debug 
        --file_type grib2
        --input_file_paths /scratch1/NCEPDEV/rstprod/com/gfs/prod/gfs.{yyyymmdd}/{hh}/atmos
        --file_name ${files}
```

## TESTS CONDUCTED: 
I've run many tests locally to try out pulling from various data sources. NOMADS never seems to work (nor does it when I run from the existing regional_workflow scripts).

## DEPENDENCIES:
Requires the packages from existing regional_workflow conda packages.

## DOCUMENTATION:
I'm not sure where it makes sense to document this tool, or if it does, since it replaces existing docs.

### CODE REVIEW

**Comment by dmwright526** [comment]
@christinaholtNOAA, Sorry for taking so long to look at this! A few comments/clarifications on the script:

-  Could you clarify the difference in the flags "--config" and "--input_file_paths"? Does "--input_file_paths" allow for not using the .yaml template?

-  Based upon the answer to the previous bullet, "--config" might need to be changed to a required input variable so better error messaging could be displayed.

- This might come more when integrating this into get_extrn* routines, but this routine will overwrite existing data in a directory. For example, the file name for HRRR from hpss does not have any date associated with the name (hrrr.t12z.wrfnatf00.grib2), so if you try to pull down more than 24 hours worth analysis data to use as boundary conditions it will overwrite data. A solution to this might be to attach the cycle_date to the start of the file name. Just a thought.

**Comment by christinaholtNOAA** [comment]
@dmwright526 Thanks for the review!

Here are a couple of responses:

> Could you clarify the difference in the flags "--config" and "--input_file_paths"? Does "--input_file_paths" allow for not using the .yaml template?

Great question. That isn't entirely clear. The `--config` flag is meant to take the `data_locations.yml` path so that the script can access known locations and file naming conventions. The `--input_file-paths` is meant to take specific paths to files on disk. This will be the mechanism for the scripts to maintain much of their existing behavior -- setting up known paths for machines (moving to config files in PR #666) or configuring it for a user-defined path. This last one is meant to be used in conjunction with the `--file_names` flag so that users can ingest files named anything...Jet for example has some different naming conventions than other platforms for historical reasons.

> Based upon the answer to the previous bullet, "--config" might need to be changed to a required input variable so better error messaging could be displayed.

I think this is a great suggestion. I think in most situations, it will be helpful to have this file information present, and isn't too expensive to load it when the information may not be needed.

> This might come more when integrating this into get_extrn* routines, but this routine will overwrite existing data in a directory. For example, the file name for HRRR from hpss does not have any date associated with the name (hrrr.t12z.wrfnatf00.grib2), so if you try to pull down more than 24 hours worth analysis data to use as boundary conditions it will overwrite data. A solution to this might be to attach the cycle_date to the start of the file name. Just a thought.

That is correct. It will overwrite files on disk (or continue downloading a partial file with wget based on the flags that are currently hard-coded). 

The output directory is set as part of the regional_workflow tasks that grab data. My plan is to put that burden on the caller such that this script can be as generic as possible. In other words, this tool should grab expected data, and put it where the user asks it to go. I think the caller should make sure it's asking for the right thing. I will make sure to provide the appropriate checks and logging in the appropriate callers to mitigate that concern. I think many of them already exist in some form or another.

One limitation of the script is that it does not loop over output directories. In the context of the regional_workflow, I believe all of the data pulling tasks (for external model data) follow this strategy of pulling only files from a single cycle in a single task. 


Let me know if that dredged up some additional questions...I'm sure it must have. Thanks again!

**Comment by dmwright526** [comment]
Thank you for the detailed response, @christinaholtNOAA ! This all makes sense to me. 

I think the final component, as you mentioned, is the documentation (which most of it is already self contained in retrieve_data.py -h). I think adding a quick description in a comment block at the top of the file would be good just to keep documentation with the file. Most of what you have written here for this PR description and in the file could be copied and pasted to give the user a starting point and for use in the User's Guide. One thing that might be good to highlight is the case sensitivity of the variables, specifically external_model.

I did test out the script on Cheyenne and it will hang if you pass hpss to it, but that would be another check to make by the caller.

Were you looking to merge this before integration?

**Comment by christinaholtNOAA** [comment]
@dmwright526 I can certainly add the documentation as you suggest. I will attempt to get to that between AMS talks this week, along with a bit of a helper to allow fewer case-sensitive concerns. I can also add a check for the compatibility of hpss calls and the machine you're on.

I would like to merge this one before integrating it, if that's okay with folks.

**Comment by dmwright526** [comment]
@christinaholtNOAA Sounds good to me.

**Comment by gsketefian** [comment]
@christinaholtNOAA I am looking through the scripts now but will approve since @dmwright526 already reviewed them.  You can merge whenever you and @dmwright526 feel it's good to go.

**Review by gsketefian — APPROVED** [review]

**Comment by christinaholtNOAA** [comment]
Thanks! I am working on addressing the comments now and will hopefully push them in the next hour or so.

**Comment by christinaholtNOAA** [comment]
@dmwright526 I believe I have addressed the concerns that you highlighted. Please take a look when you have time and let me know if that is sufficient. I'm happy to make further adjustments.

**Comment by dmwright526** [comment]
@christinaholtNOAA This all looks great to me! I will go ahead and merge.

**Pull request merged**
