### PR TITLE
Update regional_workflow for use with authoritative UFS_UTILS utilities and add support for global/regional grib2 functionality in chgres_cube 

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
## DESCRIPTION OF CHANGES: 
**This PR must be tested with [PR #17](https://github.com/ufs-community/ufs-srweather-app/pull/17) from ufs-srweather-app**

- Modifies j-jobs/exregional scripts to work with a single UFS_UTILS repository and the new version of chgres_cube, up-to-date with the authoritative UFS_UTILS repository.

- Adds support for Thompson climatology code within chgres_cube when using external model data that does not contain the ice- and water-friendly aerosol fields for Thompson MP.  Fixed file for Thompson climatology code needs to be propagated to other platforms (currently resides only on Jet and Hera in ${FIXam}).

- Adds support for the new regional_grid without alpha and kappa parameters in the namelist (these variables are optimized in the new version of the code)

- Removes all utilities (/sorc directory) from regional_workflow

- Sources modulefiles from UFS_UTILS for build and run-time (removes "modulefiles/codes" directory and no longer uses fixed make_grid, mosaic_file, and global_equiv_resol modulefiles from "modulefiles/tasks")

- Removes all unnecessary surface-related variables and processing from exregional_make_lbcs.sh

## TESTS CONDUCTED: 
Tested successfully on Hera.  Needs to be tested on at least Jet, WCOSS, and Cheyenne.

~~Note: Not all external model data and SDF combinations are supported by chgres_cube.  Combining RAP or HRRR external model data with a Noah MP SDF will fail, since interpolation of 9 to 4 soil layers has not yet been implemented.~~ **Fixed in subsequent commit to Larissa's fork of UFS_UTILS.**  ~~Using FV3GFS model data with an SDF containing RUC-LSM (4 to 9 soil levels) has a known bug that will be fixed shortly.~~ - **Fixed in subsequent commit to this PR.** 

## CONTRIBUTORS (optional): 
@LarissaReames-NOAA

### CODE REVIEW

**Comment by mkavulich** [comment]
Quick question, sorry if it's naive as I haven't had time to fully absorb all the changes. Is the removal of wgrib2 paths in regional_workflow because it can now be sourced from NCEPLIBS?

**Comment by JeffBeck-NOAA** [comment]
Not from NCEPLIBS, but from the WGRIB2_ROOT environment variable that is
defined in the build.${MACHINE} module file that's used for both build and
run-time environments.

**Comment by JulieSchramm** [comment]
I can't get the utilities to build on Cheyenne.

**Comment by gsketefian** [comment]
@JeffBeck-NOAA I tried running on Jet but found errors that I realized will also cause the tests to fail on Hera.  So I decided to test on Hera first (I will retry on Jet once the Hera ones are resolved).  I ran all 26 WE2E tests, and the results are below.  17 succeeded and 9 failed.  A couple of them are easy to fix, but others I'm not sure about.  Also, we can remove some of the outdated tests (e.g. ones with old physics suites).

GSD_RAP13km fails in run_post tasks (6 of 7 run_post tasks fail).  Error message for run_post_f00 is:
-----------------------------------
 id(18),tinvstat,IFHR,ITMAXMIN in rhmax=            0           0           0
           1
 id(18),tinvstat,IFHR,ITMAXMIN in rhmax=            0           0           0
           1
srun: error: h35m21: task 32: Exited with exit code 174
srun: Terminating job step 10797800.0
slurmstepd: error: *** STEP 10797800.0 ON h35m17 CANCELLED AT 2020-08-26T04:03:55 ***
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
ncep_post          0000000000FA3BAE  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B368AA155F0  Unknown               Unknown  Unknown
ncep_post          00000000010805E0  Unknown               Unknown  Unknown
forrtl: error (78): process killed (SIGTERM)

community_ensemble_008mems succeeds.
-----------------------------------

community_ensemble_2mems succeeds.
---------------------------------

nco_GSD_HRRR3km_FV3GFS_FV3GFS succeeds.
--------------------------------------

nco_GSD_HRRR3km_HRRRX_RAPX fails in the run_fcst task:
-----------------------------------------------------
 ThompMP: computing freezeH2O
 ThompMP: computing freezeH2O
 ThompMP: computing freezeH2O
 ThompMP: computing freezeH2O
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
fv3_gfs.x          000000000331871C  Unknown               Unknown  Unknown
libpthread-2.17.s  00002AEC81ED75F0  Unknown               Unknown  Unknown
libiomp5.so        00002AEC825145DB  Unknown               Unknown  Unknown

nco_conus succeeds.
------------------

nco_conus_c96 succeeds.
----------------------

nco_ensemble succeeds.
---------------------

new_ESGgrid succeeds.
--------------------

regional_001 succeeds.
---------------------

regional_002 succeeds.
---------------------

regional_003 fails on the make_ics task with the following error:
----------------------------------------------------------------
\- CALL FieldScatter FOR INPUT GRID VEG GREENNESS.
\- CALL FieldScatter FOR INPUT GRID VEG GREENNESS.
\- READ VEG FRACTION.
         18
\- FATAL ERROR:
COULD NOT FIND VEGETATION FRACTION IN FILE.  PLEASE SET VGFRC_FROM_CLIMO=.TRUE.
 EXITING
\- IOSTAT IS:            0
forrtl: severe (174): SIGSEGV, segmentation fault occurred
...


regional_004 fails on the make_ics task with the following error:
----------------------------------------------------------------
\- CALL FieldScatter FOR INPUT GRID VEG GREENNESS.
\- CALL FieldScatter FOR INPUT GRID VEG GREENNESS.
\- READ VEG FRACTION.
         18
\- FATAL ERROR:
COULD NOT FIND VEGETATION FRACTION IN FILE.  PLEASE SET VGFRC_FROM_CLIMO=.TRUE.
 EXITING
\- IOSTAT IS:            0
forrtl: severe (174): SIGSEGV, segmentation fault occurred
...


regional_005 test fails in the run_fcst task:
--------------------------------------------
NOTE from PE     0: MPP_IO_SET_STACK_SIZE: stack size set to     246272.
 netcdf      Write Time is    0.03501 at Fcst   06:00
 ichunk2d,jchunk2d           1           1
 ichunk3d,jchunk3d,kchunk3d           1           1          64
 mask_fields time is    0.00628
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
fv3_gfs.x          000000000331871C  Unknown               Unknown  Unknown
libpthread-2.17.s  00002BA5291E35F0  Unknown               Unknown  Unknown
fv3_gfs.x          00000000033023B5  Unknown               Unknown  Unknown
...

regional_006 succeeds.
---------------------

regional_007 succeeds.
---------------------

regional_008 succeeds.
---------------------

regional_009 succeeds.
---------------------

regional_010 fails in make_ics task:
-----------------------------------
 72 ERROR:                                                                   
 73   From script:  "exregional_make_ics.sh"                                 
 74   Full path to script:  "/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/ufs-srweather-app_Jeff_UFS_UTILS/regional_workflow/scripts/exregional_make_ics.    sh"
 75 A variable mapping table has not yet been defined for this physics suite:
 76   CCPP_PHYS_SUITE = "FV3_CPT_v0"                                         
 77 Exiting with nonzero status.                                             

regional_011 succeeds.
---------------------

regional_012 succeeds.
---------------------

regional_013 fails in run_fcst task:
-----------------------------------
 fv_restart_end u    =    2305843009213693952                            
 fv_restart_end v    =    2305843009213693952                            
 fv_restart_end w    =    2305843009213693952                            
 fv_restart_end delp =    2305843009213693952                            
 fv_restart_end phis =    3541545870036798852                            
 fv_restart_end pt   =    2305843009213693952                            
 fv_restart_end q(prog) nq   =          13  -6917529027641081856         
 fv_restart_end sphum =    2305843009213693952                           
 fv_restart_end liq_wat =    2305843009213693952                         
 fv_restart_end ice_wat =    2305843009213693952                         
 fv_restart_end rainwat =    2305843009213693952                         
 fv_restart_end snowwat =    2305843009213693952                         
 fv_restart_end graupel =    2305843009213693952                         
 fv_restart_end water_nc =    2305843009213693952                        
 fv_restart_end ice_nc =    2305843009213693952                          
 fv_restart_end rain_nc =    2305843009213693952                         
 fv_restart_end o3mr =    2305843009213693952                            
 fv_restart_end liq_aero =    2305843009213693952                        
 fv_restart_end ice_aero =    2305843009213693952                        
 fv_restart_end sgs_tke =    2305843009213693952                         
 ZS   3557.82543945312       -52.1903877258301        538.051376006237   
                                                                         
FATAL from PE     0: NaN in input field of mpp_reproducing_sum(_2d), this indicates numerical instability
                                                                         
                                                                         
FATAL from PE     1: NaN in input field of mpp_reproducing_sum(_2d), this indicates numerical instability
                                                                         
                                                                         
FATAL from PE     2: NaN in input field of mpp_reproducing_sum(_2d), this indicates numerical instability


regional_014 fails in make_ics task:  (I think I know the reason for this failure.)
-----------------------------------
 \- FATAL ERROR: CANT DETERMINE CRES FROM MOSAIC FILE.
 \- IOSTAT IS:            1
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
chgres_cube.exe    0000000001A6A6ED  Unknown               Unknown  Unknown
libpthread-2.17.s  00002AC0607005F0  Unknown               Unknown  Unknown
libmpifort.so.12.  00002AC05F70EC54  mpi_abort             Unknown  Unknown
chgres_cube.exe    00000000005118ED  error_handler_             11  utils.f90
chgres_cube.exe    00000000004CE6AC  program_setup_mp_         260  program_setup.f90
chgres_cube.exe    00000000004356B0  MAIN__                     63  chgres.F90
chgres_cube.exe    000000000041FC3E  Unknown               Unknown  Unknown
libc-2.17.so       00002AC061531505  __libc_start_main     Unknown  Unknown
chgres_cube.exe    000000000041FB43  Unknown               Unknown  Unknown
srun: error: h15c11: tasks 0-11: Exited with exit code 174
srun: Terminating job step 10796143.0
srun: error: h16c03: tasks 12-23: Exited with exit code 174
srun: error: h20c01: tasks 36-47: Exited with exit code 174
srun: error: h17c12: tasks 24-35: Exited with exit code 174

regional_015 succeeds.
---------------------

regional_016 fails in run_fcst task:
-----------------------------------
n_split loop, it=           2
delz     -40.8883013184397       -8741.84047922795                          NaN
delz     -40.8883013184397       -8741.84047922795                          NaN
delz updated     -40.8883013184397       -8741.84047922795
                     NaN

user_staged_extrn_files succeeds.
--------------------------------

**Comment by JeffBeck-NOAA** [comment]
@gsketefian Can you please rerun the WE2E tests?  I pushed a fix to make climo fields the default for all soil variables when creating external model data.  This is required because HRRRX surface data fields are only available for certain dates, and the onus should be on the user to make that switch manually.  I'm hoping this will fix your vegetation fraction errors.

**Comment by gsketefian** [comment]
@JeffBeck-NOAA Ok, I will retest regional_003 and regional_004 because those seem to be the only ones affected by veg fraction errors.  Let me know if there are other I should retest.

Also, regional_010 seems like an easy one to fix -- just need to add FV3_CPT_v0 to the if-statement.  What do you think?

**Comment by JeffBeck-NOAA** [comment]
@gsketefian The latest commit added FV3_CPT_v0 to the if-statement, so you should be ready to go for a new set of WE2E tests.

**Comment by gsketefian** [comment]
@JeffBeck-NOAA I retested regional_003, regional_004, and regional_010.  For regional_003 and regional_004, your fix to use the climo fields as the default for soil variables worked to get around the errors in the make_ics task, but there is now an error in the run_fcst tasks (see below).  Also, your fix for FV3_CPT_v0 got regional_010 to get past the make_ics task, but there is an error in the run_fcst task (but that was already there before your PR).  Below are the results from these tests.

regional_003 fails on the run_fcst task with the following error: (may be a NetCDF and/or ESMF version error?  Happens at the end of the forecast.)
----------------------------------------------------------------
 liq_aero   21068661048.2037        11090306.8847389
   4842580686.03636
 ice_aero   6109319.70014047        1.92276918917294
   1927071.76019166
 sgs_tke   41.6124659992257       9.989285413561202E-005   1.01037355720486
 mask_fields time is    0.01077
NOTE from PE     0: MPP_IO_SET_STACK_SIZE: stack size set to    1420800.
 netcdf      Write Time is    0.18635 at Fcst   06:00
 ichunk2d,jchunk2d           1           1
 ichunk3d,jchunk3d,kchunk3d           1           1          64
 mask_fields time is    0.01319
 netcdf      Write Time is    0.25518 at Fcst   06:00
 total            Write Time is    0.47485 at Fcst   06:00
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
fv3_gfs.x          000000000331871C  Unknown               Unknown  Unknown
libpthread-2.17.s  00002AEE8592C5F0  Unknown               Unknown  Unknown
libiomp5.so        00002AEE85F6EFD1  Unknown               Unknown  Unknown
libiomp5.so        00002AEE85F6ED44  Unknown               Unknown  Unknown
libiomp5.so        00002AEE85F70B55  Unknown               Unknown  Unknown
libiomp5.so        00002AEE85F72BD6  Unknown               Unknown  Unknown
libiomp5.so        00002AEE85F71D69  Unknown               Unknown  Unknown
fv3_gfs.x          0000000003353849  Unknown               Unknown  Unknown
fv3_gfs.x          000000000241908E  Unknown               Unknown  Unknown
fv3_gfs.x          000000000230CB07  Unknown               Unknown  Unknown
fv3_gfs.x          0000000000DE32AF  Unknown               Unknown  Unknown
fv3_gfs.x          0000000000D59E84  Unknown               Unknown  Unknown
fv3_gfs.x          0000000000AD8F90  Unknown               Unknown  Unknown
fv3_gfs.x          0000000000AE58D4  Unknown               Unknown  Unknown
fv3_gfs.x          00000000004EF6E2  Unknown               Unknown  Unknown
fv3_gfs.x          00000000004B7B26  Unknown               Unknown  Unknown
libesmf.so         00002AEE80CF0ED1  _ZN5ESMCI6FTable1        2010  ESMCI_FTable.C
libesmf.so         00002AEE80CF4AB6  ESMCI_FTableCallE         746  ESMCI_FTable.C
libesmf.so         00002AEE811E078A  _ZN5ESMCI2VM5ente        1178  ESMCI_VM.C
libesmf.so         00002AEE80CF2507  c_esmc_ftablecall         898  ESMCI_FTable.C
libesmf.so         00002AEE81423491  esmf_compmod_mp_e        1209  ESMF_Comp.F90
libesmf.so         00002AEE816DFE34  esmf_gridcompmod_         818  ESMF_GridComp.F90
fv3_gfs.x          00000000004AD607  Unknown               Unknown  Unknown

regional_004 fails on the run_fcst task with the following error: (may be an ESMF version error?  Happens at the beginning of the forecast.)
--------------------------------------------------------------------------------
 ThompMP: computing freezeH2O
 ThompMP: computing freezeH2O
 ThompMP: computing freezeH2O
 Writing qr_acr_qs.dat in Thompson MP init
Computing rain collecting snow table took     22.221 seconds.
   creating freezing of water drops table
 ThompMP: computing freezeH2O
 ThompMP: computing freezeH2O
 ThompMP: computing freezeH2O
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
fv3_gfs.x          000000000331871C  Unknown               Unknown  Unknown
libpthread-2.17.s  00002ADF7762F5F0  Unknown               Unknown  Unknown
fv3_gfs.x          0000000002A67149  Unknown               Unknown  Unknown
fv3_gfs.x          00000000027CA9C0  Unknown               Unknown  Unknown
fv3_gfs.x          00000000027C4108  Unknown               Unknown  Unknown
fv3_gfs.x          00000000009FE892  Unknown               Unknown  Unknown
fv3_gfs.x          00000000009F8D30  Unknown               Unknown  Unknown
fv3_gfs.x          00000000004F2482  Unknown               Unknown  Unknown
fv3_gfs.x          00000000004B9D8F  Unknown               Unknown  Unknown
libesmf.so         00002ADF729F3ED1  _ZN5ESMCI6FTable1        2010  ESMCI_FTable.C
libesmf.so         00002ADF729F7AB6  ESMCI_FTableCallE         746  ESMCI_FTable.C
libesmf.so         00002ADF72EE378A  _ZN5ESMCI2VM5ente        1178  ESMCI_VM.C
libesmf.so         00002ADF729F5507  c_esmc_ftablecall         898  ESMCI_FTable.C
libesmf.so         00002ADF73126491  esmf_compmod_mp_e        1209  ESMF_Comp.F90
libesmf.so         00002ADF733E5A84  esmf_gridcompmod_        1405  ESMF_GridComp.F90
fv3_gfs.x          00000000004B0026  Unknown               Unknown  Unknown

regional_010 fails on the run_fcst task with the following error: (This was happening before this PR as well; seems like something is wrong with the namelist file.)
--------------------------------------------------------------------------------
 After adi: W max =    1.42018655872571       min =   -1.13752550800173
 na_ini Z500   5705.80208244194        5705.80208244194
  0.000000000000000E+000  0.000000000000000E+000
forrtl: severe (19): invalid reference to variable in NAMELIST input, unit -5, file Internal Formatted NML Read, line -1, position 13
Image              PC                Routine            Line        Source
fv3_gfs.x          0000000003310CB2  Unknown               Unknown  Unknown
fv3_gfs.x          00000000033456AF  Unknown               Unknown  Unknown
fv3_gfs.x          00000000033435DB  Unknown               Unknown  Unknown
fv3_gfs.x          000000000269EA68  Unknown               Unknown  Unknown
fv3_gfs.x          00000000032F8E0A  Unknown               Unknown  Unknown
fv3_gfs.x          00000000031EAF45  Unknown               Unknown  Unknown
fv3_gfs.x          00000000004F1F42  Unknown               Unknown  Unknown
fv3_gfs.x          00000000004B9D8F  Unknown               Unknown  Unknown
libesmf.so         00002B334F623ED1  _ZN5ESMCI6FTable1        2010  ESMCI_FTable.C
libesmf.so         00002B334F627AB6  ESMCI_FTableCallE         746  ESMCI_FTable.C
libesmf.so         00002B334FB1378A  _ZN5ESMCI2VM5ente        1178  ESMCI_VM.C
libesmf.so         00002B334F625507  c_esmc_ftablecall         898  ESMCI_FTable.C
libesmf.so         00002B334FD56491  esmf_compmod_mp_e        1209  ESMF_Comp.F90
libesmf.so         00002B3350015A84  esmf_gridcompmod_        1405  ESMF_GridComp.F90
fv3_gfs.x          00000000004B0026  Unknown               Unknown  Unknown
libesmf.so         00002B334F623ED1  _ZN5ESMCI6FTable1        2010  ESMCI_FTable.C

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, can you point me to the full log files?  Thanks!

**Comment by gsketefian** [comment]
The regional_014 test will be fixed as long as [this PR](https://github.com/LarissaReames-NOAA/UFS_UTILS/pull/15) makes its way into the feature/regional_release branch of Larissa's UFS_UTILS fork.

**Comment by gsketefian** [comment]
Here's a summary of the latest failed tests.  I'd say start with trying to fix nco_GSD_HRRR3km_HRRRX_RAPX because that's what GSL wants to run.  The experiment directories for all the WE2E tests I ran for this PR can be found under here (on hera):

/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/expt_dirs/PR274_UFS_UTILS_20200902

Below, I list the test name followed by the grid, suite, and external model for ICs/LBCs that the test uses.  Then the bullet points state which task fails and other info.  You can look in the log files for detailed error messages.

**GSD_RAP13km -- GSD_RAP13km, FV3_GSD_v0, FV3GFS/FV3GFS:**
* 6 of 7 run_post tasks fail.
* Probably a bug in EMC_post.  Not a priority to fix since this grid is not supported.

**nco_GSD_HRRR3km_HRRRX_RAPX -- GSD_HRRR3km, FV3_GSD_SAR, HRRRX/RAPX:**
* run_fcst task fails.
* The error is the same as for test regional_004, I think (error in ThompMP).

**regional_003 -- GSD_HRRR25km, FV3_GSD_v0, HRRRX/RAPX:**
* run_fcst task fails.

**regional_004 -- GSD_HRRR25km, FV3_GSD_SAR, HRRRX/RAPX:**
* run_fcst task fails.
* The error is the same as for test nco_GSD_HRRR3km_HRRRX_RAPX, I think (error in ThompMP).

**regional_005 -- GSD_HRRR_AK_50km, FV3_GSD_SAR, RAPX/RAPX:**
* run_fcst task fails.

**regional_010 -- GSD_HRRR25km, FV3_CPT_v0, GSMGFS/GSMGFS:**
* run_fcst task fails.
* Probably something is wrong with the namelist file.
* Not a priority to fix right now since this problem already exists in the develop branch.

**regional_013 -- GSD_HRRR25km, FV3_GSD_SAR_v1, GSMGFS/GSMGFS:**
* run_fcst task fails.
* Not a priority since the FV3_GSD_SAR_v1 suite is deprecated.

**regional_014 -- GSD_HRRR25km, FV3_GFS_2017_gfdlmp, GSMGFS/GSMGFS:**
* Will fail in make_ics task UNLESS PR#[15 ](https://github.com/LarissaReames-NOAA/UFS_UTILS/pull/15
)into Larissa's fork/branch is merged.

**regional_016 -- GSD_HRRR25km, FV3_RRFS_v0, GSMGFS/GSMGFS:**
* run_fcst task fails
* Not a priority since the FV3_RRFS_v0 suite is deprecated.

**Comment by JeffBeck-NOAA** [comment]
@gsketefian Latest commits should fix your WE2E errors.

**Comment by JeffBeck-NOAA** [comment]
@gsketefian Latest commit should fix your WE2E errors.

**Comment by gsketefian** [comment]
@JeffBeck-NOAA I reran the failed tests.  The NCO-mode one (nco_GSD_HRRR3km_HRRRX_RAPX) works but the others still fail because of the bugs in PR #280 that are currently in the HEAD of develop.  I have a bugfix that I will push this afternoon which you'll have to merge and then we can rerun the community mode tests.

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, sounds good.  I will merge as soon as it's available.

**Comment by gsketefian** [comment]
@JeffBeck-NOAA I just checked this out but it doesn't have my latest PR.  Can you merge the latest develop into this so I can retest?  Thx.

**Comment by JeffBeck-NOAA** [comment]
Yes. Doing that now.

**Comment by gsketefian** [comment]
@JeffBeck-NOAA Can you update your PR#17 into ufs-srweather-app so that it uses the release/public-v2 branch? The current ufs-weather-model does not have the RRFS_v1beta suite defined yet (SDF is missing).

**Comment by gsketefian** [comment]
@JeffBeck-NOAA Also, can you check if the FV3_CPT_v0 suite accidentally got deleted from the make_ics.sh and make_lbcs.sh scripts where the variable mapping table is set?  This is the error I'm getting from the make_ics.sh script (from test regional_010, which uses the FV3_CPT_v0 suite):
```
ERROR:                                                                   
  From script:  "exregional_make_ics.sh"                                 
  Full path to script:  "/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/ufs-srweather-app_Jeff_UFS_UTILS/regional_workflow/scripts/exregional_make_ics.sh"
A variable mapping table has not yet been defined for this physics suite:
  CCPP_PHYS_SUITE = "FV3_CPT_v0"                                         
Exiting with nonzero status.                                             
+ print_err_msg_exit 'Call to ex-script corresponding to J-job "JREGIONAL_MAKE_ICS" failed.'
```
Same error from the make_lbcs.sh script.  Thanks.

**Comment by JeffBeck-NOAA** [comment]
@gsketefian I added the FV3_CPT_v0 SDF to the necessary lines in the make_ics/lbcs script.  It should work now.

**Comment by gsketefian** [comment]
@JeffBeck-NOAA Ok, the FV3_CPT_v0 issue is fixed.  Also, the RRFV_v1beta suite is now available in ufs-weather-model.  BUT, because we're now using regional_esg_grid instead of the old regional_grid to generate grids, the orography statistics files that Mike Toy made no longer work.  Most importantly, there is an unknown grid number issue in the tests that use HRRRX or RAPX for the ICs, which is probably the most important problem to fix (it wasn't there before I pulled your latest commits).  Below is a summary of the latest WE2E test results on hera:

```
FV3_RRFS_v1beta                   FAILURE - Don't have the orography statistics files for new grids generated by regional_esg_grid (e.g. C401 vs. C403).
GSD_RAP13km                       FAILURE - Many of the run_post tasks die.  They seem to hang, then time-out when the job runs out of time.
community_ensemble_008mems        SUCCESS                                
community_ensemble_2mems          SUCCESS                                
nco_GSD_HRRR3km_FV3GFS_FV3GFS     SUCCESS                                
nco_GSD_HRRR3km_HRRRX_RAPX        FAILURE - Unknown input file grid template number. Must be one of: 3, 3.30, 3.32769
nco_conus                         SUCCESS                                
nco_conus_c96                     SUCCESS                                
nco_ensemble                      SUCCESS                                
new_ESGgrid                       SUCCESS                                
regional_001                      SUCCESS                                
regional_002                      SUCCESS                                
regional_003                      FAILURE - Unknown input file grid template number. Must be one of: 3, 3.30, 3.32769
regional_004                      FAILURE - Unknown input file grid template number. Must be one of: 3, 3.30, 3.32769
regional_005                      FAILURE - Unknown input file grid template number. Must be one of: 3, 3.30, 3.32769
regional_006                      SUCCESS                                   
regional_007                      SUCCESS                                   
regional_008                      SUCCESS                                   
regional_009                      SUCCESS                                 
regional_010                      FAILURE - in run_fcst task (expected)  
regional_011                      SUCCESS                                   
regional_012                      SUCCESS                                   
regional_014                      SUCCESS                                   
regional_015                      SUCCESS                                   
user_staged_extrn_files           SUCCESS                                
```

**Comment by JeffBeck-NOAA** [comment]
@gsketefian Recent changes in the UFS_UTILS build.hera module file have broken wgrib2 on Hera.  I just left a comment for the commit in UFS_UTILS that has these changes and detailed what the problem is.  This is the source of the problem with an "unknown input file grid".  Chgres_cube is unable to run wgrib2 on the input file to identify what kind of grid it is.

**Comment by gsketefian** [comment]
As of 20200918, on hera all WE2E tests pass except for the following three, which are expected to fail:
```
FV3_RRFS_v1beta       FAILURE - In make_orog:  Don't have the orography statistics files for new grids generated by 
                                regional_esg_grid (e.g. C401 vs. C403).  These are not available because the change from 
                                the regional_grid to regional_esg_grid code slightly modifies the grid files, and the 
                                corresponding orography statistics files are not yet available.
GSD_RAP13km           FAILURE - Many of the run_post tasks die.  They seem to hang, then time-out when the job runs out 
                                of time.  This failure is either due to the new EMC_post branch being used or to the 
                                change from the regional_grid to the regional_esg_grid code.
regional_010          FAILURE - In run_fcst task (expected).  This is due to an error in the FV3 namelist file (probably 
                                an incorrect variable name).
```
Since this PR needs to go in urgently, I will approve it along with with [PR #17](https://github.com/ufs-community/ufs-srweather-app/pull/17) to ufs-community/ufs-srweather-app.

**Review by gsketefian — APPROVED** [review]

**Pull request merged**
