### PR TITLE
Add CODEOWNERS file with Julie, Mike, Gerard and Jeff as owners.

### PR DESCRIPTION
**Pull request by JulieSchramm**
@jwolff-ncar

### CODE REVIEW

**Comment by gsketefian** [comment]
Looks good.  How can I tell who the reviewers are (besides me) for this PR?  I want to know if anyone else approved yet.  The page for this PR does not list other reviewers.  Maybe I'm the only one?  If so, let me know and I can merge, too.

**Comment by llpcarson** [comment]
Until this CODEOWNERS file goes in, there are no reviewers assigned automatically . Julie (or you?) could add someone individually, upper right column - there should be a drop-down menu to add people.  Even with this commit, one can add more reviewers on any individual PR.

Additionally, someone will need to add a "branch protection" rule, to require some minimum # of reviews to merge a PR, for this branch.

**Comment by gsketefian** [comment]
Ok, I just added a branch protection rule for the community_develop branch to have at least 2 reviews to merge a PR.  I will merge the PR now, probably no need to add new reviewers.

**Comment by gsketefian** [comment]
Need 2 reviewers because I just changed the branch protection rules to require that.  I just added Laurie and Jamie as reviewers (can't add Julie because she initiated the PR, I think).  Whichever of you approves it first, you can go ahead and merge as well, I think.

**Comment by llpcarson** [comment]
Gerard (and Jamie) - I approved the PR, but am apparently not an approved-reviewer, probably I don't have the correct permissions for this repo.

**Comment by JulieSchramm** [comment]
I can't merge it either.

**Comment by llpcarson** [comment]
It's all in the timing!  I just merged this one, thanks Gerard!

**Pull request merged**
