### PR TITLE
Feature/ufs sr wx app Version of regional workflow to use with ufs-srweather-app

### PR DESCRIPTION
**Pull request by JulieSchramm**
- Modifications to regional workflow to allow use with the ufs-srweather-app umbrella repository.

- Note that when this PR is merged, the regional_workflow will not run as a standalone workflow. It will have to be used with the ufs-srweather-app repository.

## DESCRIPTION OF CHANGES: 
- The build scripts in the sorc directory have been removed and now reside in the ufs-srweather-app src directory.
- manage_externals has been removed and is now located in the ufs-srweather-app umbrella repository
- Changes have been made in the workflow to use the new directory structure in the ufs-srweather-app

## TESTS CONDUCTED: 
Build is successful on Cheyenne. Workflow runs to completion on Cheyenne. Model output looks reasonable.

### CODE REVIEW

**Comment by JulieSchramm** [comment]
When this is merged into develop, I will modify the Externals.cfg to point
to the develop branch and Jeff will have updated hashes for the utilities
due to the changes on jet.

**Comment by mkavulich** [comment]
Are those updated hashes ready to go? I can merge this PR whenever you're ready.

**Comment by JulieSchramm** [comment]
There is an issue with the module.nems file not being generated with the
build.

**Comment by JulieSchramm** [comment]
The workflow runs to completion on Hera and Cheyenne.

**Comment by JulieSchramm** [comment]
Hi Mike,

Do you want to do the merge now?

Thanks,

Julie

**Comment by gsketefian** [comment]
I just ran one WE2E test successfully with the same change in the fv3 module path as Julie.  So I'm ok with merging now (I think Jeff will do a separate PR to fix things up on jet).

I'll run the full suite of tests on hera once this PR is merged.

**Pull request merged**
