### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by JulieSchramm**
## DESCRIPTION OF CHANGES: 
* Add dependencies section to existing PR template
* Add templates for bug and feature issues
* This will provide better guidance for developers on what information to provide when submitting an issue or PR, and allow better organization/prioritization of PRs and issues for code management.
* See: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

## TESTS CONDUCTED: 
None required
## DOCUMENTATION:
None required

### CODE REVIEW

**Comment by mkavulich** [comment]
@JulieSchramm Can you just put some brief details about how this will work once the PR is merged? Even a link to Github documentation for these kinds of templates would suffice.

Aside from that I like the text and the breakdown of sections. Definitely a good start for getting issues more organized.

**Comment by mkavulich** [comment]
This is the sort of documentation I was referring to, I'm not sure if there's a better or more relevant page though: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

**Comment by JulieSchramm** [comment]
@mkavulich I'm not sure what your question is.  Do you want me to add the link to the template files, or add more information to the comments?

**Review by mkavulich — APPROVED** [review]
@JulieSchramm I was referring to the text of the PR (under description of changes). As it stands it is unclear what this PR would accomplish without the context of that Github functionality. I thought it would be beneficial information to have in the PR (for reviewers) and the commit log (for future historians).

It's not a pressing issue so I'll approve this PR, but I'd at least like to have a link to how Github issue templates work, if not a brief description, in the description of changes.

**Comment by JulieSchramm** [comment]
@mkavulich I modified the "Description of Changes" for this PR for reviewers (probably too late) and the commit log.

**Pull request merged**
