### PR TITLE
 Add nrows to input.nml and apply HALO_BLEND user-defined value during generate step.

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
Do not merge until after new UFS_UTILS PR is merged. This PR was created from the feature/chgres_cube branch of my fork.

## DESCRIPTION OF CHANGES: 
Halo blending was not working correct, since the "nrows_blend" value was never added to input.nml.FV3.  This PR adds nrows to input.nml and applies the HALO_BLEND user-defined value during the generate step.

## TESTS CONDUCTED: 
Tested on Hera.

### CODE REVIEW

**Comment by gsketefian** [comment]
@JeffBeck-NOAA I recommend starting this PR from the develop branch.  I think you started from your UFS_UTILS PR, and that's why it's showing 77 files changed (unless you're a lightning-fast typist).  Otherwise you're going to have to deal with a lot of merge conflicts (not to mention it's difficult for reviewers to look through 77 files to find the ones just for this PR!).

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, you're correct.  That's why I had added the "do not merge until the UFS_UTILS PR is merged" at the beginning of the PR.  I figured that the majority of changes will be removed once the other PR goes in and it will be much easier to compare.  If I'm mistaken in that, I can go ahead and change things.

**Comment by gsketefian** [comment]
@JeffBeck-NOAA Even though most of the files will be identical after the UFS_UTILS PR merge, all the changes in that PR will show up as conflicts because the history of this branch and develop will be different -- because we're doing squash-and-merge (so that all the changes for the UFS_UTILS PR will be under one commit, whereas the same changes here will be spread out over however many commits were squashed to make that one commit).  To get the histories of the two branches to be the same, you have to start with develop.  Or, you'll have to do rebasing, which is a hassle.  If this PR is pretty independent of the UFS_UTILS one, it's probably much easier to start with the current develop.  I know all this because this is exactly what I used to do.  That's how I had to learn about rebasing...

**Comment by JeffBeck-NOAA** [comment]
@gsketefian Thanks for the clarification!  That makes sense, and I certainly don't want to have to deal with rebasing things.  If I recreate this PR from develop, and the UFS_UTILS PR goes in first, I can always merge in the commits from the updated develop branch.

**Pull request closed without merging**
