### PR TITLE
Changes to MET config files to add F/OBAR output and a few other minor modifications

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
## DESCRIPTION OF CHANGES: 
Add F/OBAR output and other modification to the MET config files.

### CODE REVIEW

**Comment by gsketefian** [comment]
@JeffBeck-NOAA The config_summer.sh and config_winter.sh changes look good, but I don't think I'm the right person to approve this PR since I know nothing about the gridstat files!

**Comment by JeffBeck-NOAA** [comment]
Thanks @gsketefian, @briannen, can you take a look quickly?  Thanks!

**Comment by briannen** [comment]
The MET config files look good!

**Comment by JeffBeck-NOAA** [comment]
Thanks, @briannen, merging now.

**Pull request merged**
