### PR TITLE
Updating develop branch with updates from the release branch 

### PR DESCRIPTION
**Pull request by jwolff-ncar**
## DESCRIPTION OF CHANGES: 
Pulling changes for python plotting made only in the release branch back to develop now that things have settled down. 

Also adding the LICENSE.md file that was added to release.

## TESTS CONDUCTED: 
Test using CONUS_25km_GFSv15p2 was conducted on hera, including plotting, and all looked good.

### CODE REVIEW

**Comment by jwolff-ncar** [comment]
@BenjaminBlake-NOAA Will you take a particularly close look at the color bar changes to make sure they are what you wanted. I pulled it directly from the release branch but couldn't remember if you wanted black or darkviolet (I thought maybe the latter but the former was there in places) so want to be sure you check that out. Thanks!

**Comment by BenjaminBlake-NOAA** [comment]
@jwolff-ncar Those color bar changes look good to me.  'darkviolet' should be added to the colorlist array, and 'black' should be added to cmap.set_over.  Thanks for checking!

**Comment by jwolff-ncar** [comment]
@BenjaminBlake-NOAA Great, thanks for checking!

**Comment by jwolff-ncar** [comment]
Please let me know if there are any comments or questions on this PR that I can address. Thank you for your review.

**Review by JulieSchramm — APPROVED** [review]
Looks good.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
