### PR TITLE
Verification updates to METplus conf files from the RRFS_baseline branch

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
## DESCRIPTION OF CHANGES: 
Verification changes related to work from the RRFS_baseline branch are being brought over to the develop branch.

## TESTS CONDUCTED: 
End-to-end tests run in the context of the RRFS physics UFS-R2O project were conducted with these changes and confirmed to work correctly.

## CONTRIBUTORS (optional): 
@michelleharrold @jwolff-ncar

### CODE REVIEW

**Comment by jwolff-ncar** [comment]
I want to add this to the conversation here to keep track of it and see if there are any further comments. For the RRFS_baseline test we had:
FCST_VAR10_NAME = HPBL
FCST_VAR10_LEVELS = Z0
OBS_VAR10_NAME = PBL
OBS_VAR10_LEVELS = L0
OBS_VAR10_OPTIONS = desc = "TKE"; censor_thresh = [ >=5000 ]; censor_val = [ -9999 ];

FCST_VAR11_NAME = HGT
FCST_VAR11_LEVELS = L0
FCST_VAR11_OPTIONS = GRIB_lvl_typ = 220;
OBS_VAR11_NAME = PBL
OBS_VAR11_LEVELS = L0
OBS_VAR11_OPTIONS = desc = "RI"; censor_thresh = [ >=5000 ]; censor_val = [ -9999 ];

There were changes to the MET code (see: https://github.com/dtcenter/MET/issues/1913) to remove the need for this. However it has not been released yet (will be included in METv10.1.0). This is just a note that if you use METv10.0 you may want to add this censor_thresh/val setting back in.

**Review by jwolff-ncar — APPROVED** [review]
Looks good to me. I will also let @michelleharrold take a quick peak.

**Comment by JeffBeck-NOAA** [comment]
> Looks good to me. I will also let @michelleharrold take a quick peak.

@jwolff-ncar, thanks for adding the note about PBL height!

**Review by michelleharrold — COMMENTED** [review]
Just gave it a look over, and everything looks good to me!

**Pull request merged**
