### PR TITLE
Update FV3 namelist settings

### PR DESCRIPTION
**Pull request by gsketefian**
@ligiabernardet pointed out the following differences in FV3 namelist settings between the SRW and MRW apps for the FV3_GFS_v15p2 suite:
1) **effr_in**: is .true. in MRW; is currently .false. in SRW
2) **lgfdlmprad**: is .true. in MRW; is currently .false. in SRW
3) **trans_trac**: is .true. in MRW; is currently .false. in SRW

This PR changes the namelist so that the SRW and MRW use the same settings of these variables for the FV3_GFS_v15p2 suite and performs other namelist fixes.

## DESCRIPTION OF CHANGES: 

**Background note:**
In order to generate the namelist file for the forecast model (input.nml), the workflow scripts start with the base namelist file input.nml.FV3 and then make (1) suite-specific changes specified in the yaml configuration file FV3.input.yml followed by (2) experiment-specific changes specified in the workflow generation script generate_FV3LAM_wflow.sh.

* With the request above that effr_in be set to .true. for the FV3_GFS_v15p2 suite, in FV3.input.yml all suites except FV3_GFS_2017_gfdlmp_regional now set effr_in to .true..  Since effr_in is currently not specified at all in input.nml.FV3 (the base namelist), for FV3_GFS_2017_gfdlmp_regional it gets set to the default value in the weather model, which is .false..  For clarity, remove this variable from all suites in FV3.input.yml except FV3_GFS_2017_gfdlmp_regional and set it to .true. input.nml.FV3.  For FV3_GFS_2017_gfdlmp_regional, set effr_in to .false. in FV3.input.yml to recover the default .false. value it needs to have.
* With the request above that trans_trac be set to .true. for the FV3_GFS_v15p2 suite, in FV3.input.yml trans_trac is (needs to be) set to .true. for two suites (FV3_GFS_v15p2 and FV3_GFS_v16) and not specified for the others.  Since this variable is already set to .true. in input.nml.FV3, for clarity remove it completely from FV3.input.yml.
* In FV3.input.yml, change lgfdlmprad from .false. to .true. for the FV3_GFS_v15p2 suite.
* In FV3.input.yml, remove the variables ccpp_suite, stretch_fac, target_lon, and target_lat from any suites that define them because these are always overwritten (in generate_FV3LAM_wflow.sh) by values specified for the current experiment.
* WE2E tests:
  * Add two new generic suite WE2E tests for the FV3_2017_gfdlmp_regional and FV3_HRRR suites (suite_FV3_GFS_2017_gfdlmp_regional and suite_FV3_HRRR).
  * Rename the regional_001 test to make it the generic test for the FV3_GFS_2017_gfdlmp suite.

## TESTS CONDUCTED:
Ran the following WE2E tests (including the two new ones and the renamed one) on Hera:

* suite_FV3_CPT_v0
* suite_FV3_GFS_2017_gfdlmp
* suite_FV3_GFS_2017_gfdlmp_regional
* suite_FV3_GFS_v15p2
* suite_FV3_GFS_v16
* suite_FV3_GSD_SAR
* suite_FV3_GSD_v0
* suite_FV3_HRRR
* suite_FV3_RRFS_v1alpha
* suite_FV3_RRFS_v1beta
* grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16

These cover the 10 currently supported suites plus an extra test for the FV3_GFS_v16 suite (grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16; need for this is explained below).  
All except suite_FV3_CPT_v0 and suite_FV3_GFS_v16 were successful.  Both failures are pre-existing ones.  Details:

1) suite_FV3_CPT_v0 failed to do an inconsistency in the namelist (probably a variable is defined in the namelist that is not defined in the weather-model code).  Initial attempts to pinpoint this variable were unsuccessful.  Note that this is a pre-existing failure.
2) suite_FV3_GFS_v16 failed in the run_fcst step after hour 1.  Attempts to replace the namelist with one from a past successful run did not make a difference.  The start of the error message is:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
1603 *** Error in `/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/PR_feature_Ligia_namelist_fix/ufs-srweather-app/bin/ufs_model': corrupted double-linked list: 0x000000000f916c90 ***
*** Error in `/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/PR_feature_Ligia_namelist_fix/ufs-srweather-app/bin/ufs_model': free(): corrupted unsorted chunks: 0x000000000f916460 ***
```
Note that this is a pre-existing failure.  To obtain a successful test for the FV3_GFS_v16 suite, the grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 test was run, and it was successful.  The differences between these two tests are that suite_FV3_GFS_v16 uses
```
LBC_SPEC_INTVL_HRS="6"
DATE_FIRST_CYCL=DATE_LAST_CYCL="20190520"
EXTRN_MDL_NAME_ICS=EXTRN_MDL_NAME_LBCS="GSMGFS"
```
while grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 uses
```
LBC_SPEC_INTVL_HRS="3"
DATE_FIRST_CYCL=DATE_LAST_CYCL="20190701"
EXTRN_MDL_NAME_ICS=EXTRN_MDL_NAME_LBCS="FV3GFS"
```

### CODE REVIEW

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by ligiabernardet** [comment]
@Man Zhang - NOAA Affiliate <man.zhang@noaa.gov> Pls update the CCPP SciDoc
accordingly. Thanks

**Comment by jwolff-ncar** [comment]
What is the status of this PR?

**Comment by JeffBeck-NOAA** [comment]
> What is the status of this PR?

@gsketefian, is this PR ready to merge?  It looks pretty straightforward.

**Comment by gsketefian** [comment]
@JeffBeck-NOAA I just remembered that the reason I hadn't merged this was because there were other bug fixes and improvements in the analogous PR #423 that I also wanted to get into this one.  But I decided to get those changes in as a separate PR (there is actually an issue for it at #428 that I just updated).  This PR is now ready to merge.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
