### PR TITLE
Update version of ESMF from 7.1.0r to 8_0_48b.netcdf47.

### PR DESCRIPTION
**Pull request by JulieSchramm**
Hera update from EMC uses ESMF 8_0_48b.netcdf47

### CODE REVIEW

**Comment by gsketefian** [comment]
Just wondering why this wasn't a problem for me on hera.

**Comment by llpcarson** [comment]
I think this is needed for the latest NEMSfv3gfs, so may show up for you when that's updated.

**Comment by climbfuji** [comment]
The target date for the offical 8.0.0 release is mid October - we should update to this version. You can use bs50 for now, which is pretty much identical to what will be released.

**Comment by JulieSchramm** [comment]
Note that this update is only for the make_sfc_climo task.  This is so the version of EMSF used for the build from the regional workflow matches what is run from the UFS_UILTS develop branch.

**Comment by climbfuji** [comment]
> Note that this update is only for the make_sfc_climo task. This is so the version of EMSF used for the build from the regional workflow matches what is run from the UFS_UILTS develop branch.

Got it, thanks for the clarification.

**Pull request closed without merging**
