### PR TITLE
RRFS_v1beta SDF changes after reverting from GSL to GFS GWD suite

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
## DESCRIPTION OF CHANGES: 
Removed checks on the RRFS_v1beta SDF implemented for use with the GSL GWD suite (now uses the GFS GWD suite).  No longer copies staged orography files necessary for the GSL GWD suite.  

## TESTS CONDUCTED: 
Runs to completion on Hera.

### CODE REVIEW

**Comment by gsketefian** [comment]
@JeffBeck-NOAA That's pretty much exactly what I did on the develop branch, specifically the removing of the line GWD_opt: 3 in the FV3.input.yml file.  Not sure why mine didn't work.

I'd give you an approve but I can't!

**Comment by JeffBeck-NOAA** [comment]
> 
> 
> @JeffBeck-NOAA That's pretty much exactly what I did on the develop branch, specifically the removing of the line GWD_OPT: 3 in the FV3.input.yml file. Not sure why mine didn't work.
> 
> I'd give you an approve but I can't!

@gsketefian Thanks for looking at the PR!  Weird that the namelist change worked for me but not for you.  I'm not sure what else would have changed?   In any case, once we hear back from GitHub next week, we'll hopefully all have our user settings back and will be able to approve PRs again!

**Comment by mkavulich** [comment]
Looks good to me, I'm running a quick Cheyenne test and then I'll approve/merge

**Review by mkavulich — CHANGES_REQUESTED** [review]
`tests/run_experiments.sh` needs to be changed to remove the check for GWD_RRFS_v1beta_BASEDIR

**Comment by JeffBeck-NOAA** [comment]
> `tests/run_experiments.sh` needs to be changed to remove the check for GWD_RRFS_v1beta_BASEDIR

Thanks @mkavulich, I forgot about modifying the regression tests.

**Comment by JeffBeck-NOAA** [comment]
> > `tests/run_experiments.sh` needs to be changed to remove the check for GWD_RRFS_v1beta_BASEDIR
> 
> Thanks @mkavulich, I forgot about modifying the regression tests.

Just pushed a commit with that change.

**Review by mkavulich — APPROVED** [review]

**Pull request merged**
