### PR TITLE
Add new FIX files for recent update on Thompson scheme

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 
- A recent update on Thompson scheme requires additional FIX files: `qr_acr_qgV2.dat` and `qr_arc_qsV2.dat`.
- The two files are added to the list of `thompson_mp_fix_files` in `ush/set_thompson_mp_fix_files.sh`.
- The two files have been added to the the `FIXgsm` directory on Hera, WCOSS dell and cray, Orion, Jet, and RZDM.

## TESTS CONDUCTED: 
- It was confirmed that the new two files were copied to the `fix_am` directory by running `generate_FV3LAM_wflow.sh`.

## ISSUE: 
- Fixes issue mentioned in #497 

## CONTRIBUTORS: 
@JiliDong-NOAA, @KateFriedman-NOAA

### CODE REVIEW

**Comment by mkavulich** [comment]
@chan-hoo just for clarification, are these new files needed in *addition* to the original `qr_acr_qg.dat` and `qr_acr_qs.dat`, or are they replacing them in future versions of the Thompson scheme?

**Comment by JiliDong-NOAA** [comment]
> @chan-hoo just for clarification, are these new files needed in _addition_ to the original `qr_acr_qg.dat` and `qr_acr_qs.dat`, or are they replacing them in future versions of the Thompson scheme?

For the recent update of Thompson scheme, I think these new files replace the original `qr_acr_qg.dat` and `qr_acr_qs.dat`. The question is if we want to keep the original files in the workflow for backward compatibility?

**Comment by chan-hoo** [comment]
@mkavulich, @JiliDong-NOAA, since these new files are for the recent update, someone might use the old version. So, in my opinion, it would be better to keep both versions (all four files) at this moment.

**Comment by JiliDong-NOAA** [comment]
> @mkavulich, @JiliDong-NOAA, since these new files are for the recent update, someone might use the old version. So, in my opinion, it would be better to keep both versions (all four files) at this moment.

agree with @chan-hoo

**Comment by JeffBeck-NOAA** [comment]
Ideally, it would be great to add an "if" statement to only copy the appropriate fixed files based on the version of Thompson MP that is run.  Aside from looking at the date associated with the ufs-weather-model hash in the Externals.cfg file (which I'm not sure is possible), maybe there's a difference in the SDF XML that can be evaluated?  In any case, I'll approve this as is for now.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
