### PR TITLE
Update Release/public v1 for changing release tag from v1.0.0 to v1.0.1

### PR DESCRIPTION
**Pull request by panll**
A few bug fixes are necessary to include in a new tag of the regional_workflow release branch (release/public-v1) for UFS SRW app training:

1) [Fix for Hera (and future platforms) due to LMOD update](https://github.com/NOAA-EMC/regional_workflow/pull/542)

2) [Fix Issue #162 filter_topo](https://github.com/NOAA-EMC/regional_workflow/pull/547)

3)[ Fix in launch_FV3LAM_wflow.sh: Add missing index to array](https://github.com/NOAA-EMC/regional_workflow/pull/513)

Impacted files include:
ush/launch_FV3LAM_wflow.sh 
scripts/exregional_make_orog.sh
modulefiles/tasks/hera/make_grid.local
modulefiles/tasks/hera/make_ics.local
modulefiles/tasks/hera/make_lbcs.local
modulefiles/tasks/hera/run_fcst.local
modulefiles/tasks/jet/make_grid.local
modulefiles/tasks/jet/make_ics.local
modulefiles/tasks/jet/make_lbcs.local
modulefiles/tasks/jet/run_fcst.local
modulefiles/tasks/orion/make_grid.local
modulefiles/tasks/orion/make_ics.local
modulefiles/tasks/orion/make_lbcs.local
modulefiles/tasks/orion/run_fcst.local
ush/load_modules_run_task.sh

### CODE REVIEW

**Comment by gsketefian** [comment]
@panll In `launch_FV3LAM_wflow.sh`, line 1, can you remove the "-l" flag?  I.e.  change
`#!/bin/bash -l
`
to
`#!/bin/bash
`
Thanks.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by jwolff-ncar** [comment]
Should this go into release/public-v1 or should there be a new branch created for this first?

**Comment by climbfuji** [comment]
> Should this go into release/public-v1 or should there be a new branch created for this first?

Per our lengthy discussions last year, release/public-v1 will be used for all 1.x.y releases ...

**Comment by jwolff-ncar** [comment]
Thanks @climbfuji. I appreciate a reliable source providing the guidance!

**Comment by panll** [comment]
Changed, thanks! @gsketefian

**Pull request merged**
