### PR TITLE
Fix directory overwrite bug in NCO mode.

### PR DESCRIPTION
**Pull request by gsketefian**
This needs to be merged after PR #221.

Summary of modifications:
------------------------
* Modify scripts to prevent simultaneously running experiments in NCO mode from writing to the same set of directories.

Tests conducted:
---------------
* All WE2E tests pass except regional_013. regional_013 doesn't pass because the physics suite used by that test (FV3_GSD_SAR_v1) doesn't actually exist in the ufs-weather-model repo.

Modifications common to more than one file (used below in listing of file-by-file modifications):
------------------------------------------------------------------------------------------------
(A) Fix/add/delete comments and/or informational and/or error messages.
(B) Remove unused code and/or fix code indentation.
(C) Set the RUN and envir variables to the name of the WE2E test name contained in EXPT_SUBDIR.  Note that even though EXPT_SUBDIR is set to a null string near the beginning of this file, the script that runs the WE2E tests inserts the name of the test into the definition of EXPT_SUBDIR (i.e. it changes the line 'EXPT_SUBDIR=""' into 'EXPT_SUBDIR="test_name"') before calling the experiment generation script.  Thus, EXPT_SUBDIR will be properly set to the name of the test when the experiment generation script is called.
(D) Bug fix - change variable name from LBC_UPDATE_INTVL_HRS to LBC_SPEC_INTVL_HRS.

File-by-file description of modifications:
-----------------------------------------

jobs/JREGIONAL_RUN_POST:
* In the definition of COMOUT, use the new workflow variable COMOUT_BASEDIR that specifies the base directory under which each cycle's UPP output directories will be placed.

tests/baseline_configs/config.nco_conus.sh: (A), (C)

tests/baseline_configs/config.nco_conus_c96.sh: (A), (C)

tests/baseline_configs/config.regional_009.sh: (A), (C)
* Change the time interval for specifying external model LBCs from 6 hrs to 3 hrs (to match what is done in all the other WE2E tests that use FV3GFS as the external model for LBCs).

tests/run_experiments.sh: (A), (B)

ush/config.community.sh: (D)

ush/config.nco.sh: (D)

ush/config_defaults.sh: (A)

ush/setup.sh: (A)
* For simplicity, combine two blocks of code that create different directories into a single block (that creates both sets of directories).
* In NCO mode, change defintion of CYCLE_BASEDIR from "$STMP/tmpnwprd/${EMC_GRID_NAME}" to "$STMP/tmpnwprd/$RUN".  This is to make it easier to associate this directory with an experiment (wich can be done by setting RUN to the experiment name in the experiment's configuration file).  That way, two experiments running simultaneously (but having different names) will not end up writing to the same CYCLE_BASEDIR (which currently can happen if the two experiments are using the same grid, i.e. the same value of EMC_GRID_NAME).
* Add COMOUT_BASEDIR as a new secondary workflow variable.  In NCO mode, set this to the base directory under which the output from the RUN_POST_TN task will be placed (i.e. the cycle-independent portion of the RUN_POST_TN task's output directory) and then check whether this directory exists (and deal with it as specified by the variable PREEXISTING_DIR_METHOD).  The goal here is to be able to uniquely associate this directory to an experiment so that simultaneously running experiments do not write their UPP outputs into the same directory (and possibly overwrite each other's results).  This directory is given by COMOUT_BASEDIR="$COMROOT/$NET/$envir", so we can uniquely associate it with an experiment by setting envir to the name of the experiment (which can be done in the experiment's configuration file).  This is why in the WE2E configuration files listed above (config.nco_conus.sh, config.nco_conus_c96.sh, and config.regional_009.sh), we set envir to the name of the experiment.  In community mode, the new variable COMOUT_BASEDIR is not used, so in that case we set it to an empty string.

### CODE REVIEW

**Comment by BenjaminBlake-NOAA** [comment]
@gsketefian Should I test this on WCOSS with my latest mods or will they not work?  They are based off of your feature/emc_fixes_with_python branch.

**Comment by gsketefian** [comment]
@BenjaminBlake-NOAA Yes, please go ahead and test.  The problem that this fixes occurred when I was running two (or more) WE2E tests in NCO mode on the same grid.  If you run one experiment at a time, you may not have seen the problem at all.  This PR builds on top of #221, which in turn builds on top of #212.  

I'm planning on sending an email to @mkavulich to see if we can get #212, #221 (which @JeffBeck-NOAA successfully tested on jet and will hopefully approve soon), this PR, and yours for WCOSS merged first, and he can do his tests on cheyenne on the cumulative result instead of having to do it for each PR.

**Comment by BenjaminBlake-NOAA** [comment]
Sounds good!  I will get started on this first thing tomorrow and can hopefully finish the testing relatively quickly.

**Comment by BenjaminBlake-NOAA** [comment]
I completed a successful test on the WCOSS Cray and Dell.  I will approve this PR and once it is merged I will submit a PR for the WCOSS port changes.

**Comment by mkavulich** [comment]
I'm running tests on Cheyenne now, but I'm curious: why is the variable rename from LBC_UPDATE_INTVL_HRS  to LBC_SPEC_INTVL_HRS listed as a "bug fix"?

**Comment by gsketefian** [comment]
@mkavulich I had made the variable name change from LBC_UPDATE_INTVL_HRS to LBC_SPEC_INTVL_HRS in a previous PR (#221) just for clarity (because this variable represents the time interval in hours between the times at which the LBCs are specified (SPEC); nothing is being updated (UPDATE) at these times).  Then @JeffBeck-NOAA pointed out a couple of places where I forgot to make the name change, so that's what I'm doing in this PR and calling it a bug fix.

**Comment by gsketefian** [comment]
@mkavulich Thanks for testing on Cheyenne.  Glad to hear it works!  

But now I'm having some difficulty with the PRs since we moved to the squash-and-merge approach.  That's why you currently see a long list of conflicts for this PR, i.e. because the history for PR #212 (and maybe #221) which this PR builds on no longer exists -- because several commits from PR #212 were removed and replaced by a single new (squash) commit.  So commits that should be recognized as common to both PRs are not, and we get lots of conflicts that have to be handled manually.

Do you have any suggestions on how to get around this?  Thx.

**Comment by BenjaminBlake-NOAA** [comment]
@gsketefian  As we discussed earlier today, I will wait until this PR gets merged into community develop before submitting a PR for the WCOSS port changes.

**Comment by gsketefian** [comment]
It seems (from reading on this issue online) that the way to deal with the problem of getting a whole bunch of new unexpected conflicts that a squash-and-merge causes is to do a rebase of a second PR that builds off an initial PR that was squashed and merged.  I haven't tried it yet.  Will do so soon and report back.

**Comment by mkavulich** [comment]
@gsketefian This is true, for PRs that have a common commit history that is *not* in the main (community_develop) branch, the later PR will have to be rebased to the community_develop before merging. It looks like this branch also has the commit history of #221, so I think that should be merged first.

 If you have some time later in the day I can walk you through the process over hangouts or something, it's not difficult but it should be done with extreme caution to avoid losing work.

**Pull request merged**
