### PR TITLE
fix filter_topo failure when GWD orog is on

### PR DESCRIPTION
**Pull request by JiliDong-NOAA**
## DESCRIPTION OF CHANGES: 
fix filter_topo failure when GWD orog is on 

## TESTS CONDUCTED: 
The changes have been tested for make_orog and it is confirmed to fix the filter_topo failure 

## DEPENDENCIES:
This PR is for Issue #568 

## DOCUMENTATION:
If this PR is contributing new capabilities that need to be documented, please also include updates to the RST files in the ufs-srweather-app repository (docs/UsersGuide/source) as supporting material.

## ISSUE (optional): 
If this PR is resolving or referencing one or more issues, in this repository or elewhere, list them here. For example, "Fixes issue mentioned in #123" or "Related to bug in https://github.com/NOAA-EMC/other_repository/pull/63"

## CONTRIBUTORS (optional): 
If others have contributed to this work aside from the PR author, list them here

### CODE REVIEW

**Review by BenjaminBlake-NOAA — APPROVED** [review]
I tested this successfully on the WCOSS Dell and am good for approving these changes.

**Review by gsketefian — APPROVED** [review]
This looks good, thanks for finding the bug!

@JiliDong-NOAA I just have a small request.  Can you create an issue to put the contents of the "if [ "${CCPP_PHYS_SUITE}" = "FV3_HRRR" ]; then" into a separate function just to make the scripts more modular?  You can assign the issue to me.  Thx.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by JiliDong-NOAA** [comment]
> This looks good, thanks for finding the bug!
> 
> @JiliDong-NOAA I just have a small request. Can you create an issue to put the contents of the "if [ "${CCPP_PHYS_SUITE}" = "FV3_HRRR" ]; then" into a separate function just to make the scripts more modular? You can assign the issue to me. Thx.

@gsketefian Done. the issue is raised. I don't think I can assign the task though (probably no access).

**Comment by JeffBeck-NOAA** [comment]
> > This looks good, thanks for finding the bug!
> > @JiliDong-NOAA I just have a small request. Can you create an issue to put the contents of the "if [ "${CCPP_PHYS_SUITE}" = "FV3_HRRR" ]; then" into a separate function just to make the scripts more modular? You can assign the issue to me. Thx.
> 
> @gsketefian Done. the issue is raised. I don't think I can assign the task though (probably no access).

Thanks @JiliDong-NOAA, I just assigned @gsketefian to the issue.  Merging this PR now.

**Pull request merged**
