### PR TITLE
Feature/ufs sr wx app Version of regional workflow to use with ufs-srweather-app

### PR DESCRIPTION
**Pull request by JulieSchramm**
- Modifications to regional workflow to allow use with the ufs-srweather-app umbrella repository plus the latest updates from the develop branch (previously community_develop).

- Note that when this PR is merged, the regional_workflow will not run as a standalone workflow.  It will have to be used with the ufs-srweather-app repository.

## DESCRIPTION OF CHANGES: 
- The build scripts in the sorc directory have been removed and now reside in the ufs-srweather-app src directory.  
- manage_externals has been removed and is now located in the ufs-srweather-app umbrella repository
- Changes have been made in the workflow to use the new directory structure in the ufs-srweather-app

## TESTS CONDUCTED: 
Build is successful on Cheyenne.  Workflow runs to completion on Cheyenne.  Model output looks reasonable.

### CODE REVIEW

**Comment by gsketefian** [comment]
Hey Julie, is [this](https://github.com/ufs-community/ufs-srweather-app/wiki/Getting-Started) documentation now updated for me to try it out?  I'd like to run it on hera to see if it works (unless you've already done it).

**Comment by JulieSchramm** [comment]
Hi Gerard,

It would be great if you could test it on hera.  The wiki documentation is
up to date.

**Comment by JeffBeck-NOAA** [comment]
I will test on Jet.

- Jeff

**Comment by JeffBeck-NOAA** [comment]
A couple of findings regarding instructions on the wiki so far:

1) The ufs-srweather-app is already on branch "master" when checked out, so
it would seem the "git checkout master" step is unnecessary.
2) Running ./manage_externals/checkout_externals also must be done without
miniconda3 or else it will fail.  The note about unloading this module
should be moved to before this step.

- Jeff

**Comment by JulieSchramm** [comment]
The Externals.cfg may have to point to the NCAR utilities you modified for
jet.

**Comment by JeffBeck-NOAA** [comment]
Yep, I am checking out the develop and feature/chgres_grib2 branches for
the NCAR fork of UFS_UTILS (commented out the hashes).  We'll need to
update those hashes to top-of-the-trunk.

Thanks, Julie!

- Jeff

**Comment by gsketefian** [comment]
@JulieSchramm:
On Jet and Hera, after June 11 the "`module use -a ...`" command has to be used to point to where the contrib packages are; "`module load contrib`" will no longer work.  See #226.  Thus, must use:
```
module use -a /contrib/miniconda3/modulefiles
module load miniconda3
conda activate regional_workflow
```
The documentation needs to be updated for this.  Thanks!

**Comment by JulieSchramm** [comment]
I am closing this PR.  I merged develop into feature/ufs_sr_wx_app on my fork, so I should do the PR from my fork also.  This reduces the number of changed files from 225 to 141 (the number removed from the build scripts and manage_externals) and resolves the conflicts.

**Comment by gsketefian** [comment]
Hi Julie,

With the previous non-cmake way of building FV3, the build used to create a module file at
`ufs_weather_model/NEMS/src/conf/modules.nems` that the workflow used to copy to its own modulefiles directory.  I can't find it any longer, so I can't run the `run_fcst` task.  Is it renamed, or is this file no longer generated by the build?

**Comment by JulieSchramm** [comment]
Hi Gerard,

I just ran into the same problem on hera.  The ufs-srweather-app uses the
ufs-community/ufs-weather-mode with the cmake build, and the module.nems
file is not generated. On Cheyenne, there is a default module that is used:

A task-specific modulefile (modulefile_path) does not exist for this task

(task_name) and machine (machine) combination:

  task_name = "run_fcst"

  machine = "cheyenne"

  modulefile_path =
"/glade/p/ral/jntp/schramm/ufs-srweather-app-fork/src/ufs_weather_model/NEMS/src/conf/modules.nems"

Will attempt to use the default modulefile (default_modulefile_path):

  default_modulefile_path =
"/glade/p/ral/jntp/schramm/ufs-srweather-app-fork/regional_workflow/modulefiles/cheyenne.default"

on hera, there is an error:

ERROR:

  From script:  "load_modules_run_task.sh"

  Full path to script:
"/scratch1/BMC/gmtb/Julie.Schramm/ufs-srweather-app/regional_workflow/ush/load_modules_run_task.sh"

The target (modulefile_path) of the symlink (modulefile_name) in the task

modules directory (modules_dir) that points to module file for this task

(task_name) does not exist:

  task_name = "run_fcst"

  modulefile_name = "run_fcst"

  modules_dir =
"/scratch1/BMC/gmtb/Julie.Schramm/ufs-srweather-app/regional_workflow/modulefiles/tasks/hera"

  modulefile_path =
"/scratch1/BMC/gmtb/Julie.Schramm/ufs-srweather-app/src/ufs_weather_model/NEMS/src/conf/modules.nems"

Can we make a hera.default file?

**Pull request closed without merging**
