### PR TITLE
Adjust RRFS_CONUS_... grids

### PR DESCRIPTION
**Pull request by gsketefian**
## DESCRIPTION OF CHANGES: 
* Adjust RRFS_CONUS_25km, RRFS_CONUS_13km, and RRFS_CONUS_3km grid parameters so that:
  * All grids, including their 4-cell-wide halos, lie completely within the HRRRX domain.
  * All grids have dimensions nx and ny that factor "nicely", i.e. they don't have factors greather than 7.
  * The write-component grids corresponding to these three native grids cover as much of the native grids as possible without going outside of the native grid boundaries.  The updated NCL scripts (see below) were used to generate the write-component grid parameters.
* For the RRFS_CONUS_13km grid, reduce the time step (DT_ATMOS) from 180sec to 45sec.  This is necessary to get a successful forecast with the GSD_SAR suite, and thus likely also the RRFS_v1beta suite.
* Modify WE2E testing system as follows:
  * Add new tests with the RRFS_CONUS_25km, RRFS_CONUS_13km, and RRFS_CONUS_3km grids that use the GFS_v15p2 and RRFS_v1beta suites (which are now the ones officially supported in the first release of the short-range weather app) instead of the GFS_v16beta and GSD_SAR suites, respectively.
  * For clarity, rename the test configuration files that use the GFS_v16beta and GSD_SAR suites so they include the suite name.
  * Update list of WE2E tests (baselines_list.txt).
* Update the NCL plotting scripts to be able to plot grids with the latest version of the workflow.

## TESTS CONDUCTED: 
On hera, ran tests with all three grids with the GFS_v15p2 and RRFS_v1beta suites (a total of 6 tests).  All were successful.

### CODE REVIEW

**Comment by JeffBeck-NOAA** [comment]
@gsketefian Testing this right now.  I see you changed the "WRTCMP_write_tasks_per_group" variable to "$(( 1*LAYOUT_Y ))" for the GSD_HRRR13km domain.  Should all other pre-defined domains be changed to that too?

**Comment by gsketefian** [comment]
@JeffBeck-NOAA That ensures that WRTCMP_write_tasks_per_group divides into ESGgrid_NY evenly (because you've already chosen LAYOUT_Y to divide into ESGgrid_NY evenly), but sometimes it can be overkill, especially on coarse grids.  But it won't do any harm.

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, unfortunately, chgres_cube is failing (for both the 13-km and 25-km domains) with the following ESMF message:

"ESMCI_Mesh_Regrid_Glue.C:313 c_esmc_regrid_create() Arguments are incompatible  - - There exist destination points (e.g. id=22033) which can't be mapped to any source cell"

This is due to grid points on the integration domain falling outside of the domain of the external model data.  Can you double check your integration domains to make sure there isn't a sliver or a few points that exists outside the HRRR domain?  Thanks!

**Comment by JeffBeck-NOAA** [comment]
I noticed you already tested these two domains on Hera.  Are you sure you used the new values for the ESGgrid in your tests?

**Comment by gsketefian** [comment]
@JeffBeck-NOAA Yes, I'm pretty sure.  The runs are here:
```
/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/PR_bugfix_adjust_CONUS_grids/expt_dirs/regional_002_25km
/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/PR_bugfix_adjust_CONUS_grids/expt_dirs/regional_002_13km

```
If you do:
```
$ cd /scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/PR_bugfix_adjust_CONUS_grids/expt_dirs/regional_002_25km/orog
$ ncdump -h C401_oro_data.tile7.halo0.nc

```
you get:
```
netcdf C401_oro_data.tile7.halo0 {
dimensions:
	lon = 208 ;
	lat = 120 ;

```
which are the new dimensions for the GSD_HRRRR25km grid.  Same for the 13km grid:
```
$ cd /scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/PR_bugfix_adjust_CONUS_grids/expt_dirs/regional_002_13km/orog
$ ncdump -h C771_oro_data.tile7.halo0.nc 
netcdf C771_oro_data.tile7.halo0 {
dimensions:
	lon = 400 ;
	lat = 240 ;

```
Check to see if you're using the same versions of the external repos as I am.  My workflow directory is at:
`/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/PR_bugfix_adjust_CONUS_grids/ufs-srweather-app`

**Comment by JeffBeck-NOAA** [comment]
Hey @gsketefian, it looks like you're stilli running the old version of the regional_grid code.  Can you try the new version (without the alpha and kappa parameters), to see if it still works for you?  Thanks!

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, I have a feeling that in tweaking the alpha and kappa parameters automatically, the new regional_grid is modifying the flaring and therefore the edges of the grid enough to have some of the grid points fall outside the operational HRRR domain.

**Comment by gsketefian** [comment]
@JeffBeck-NOAA Oh, I totally forgot about the two different codes.  I can try using Larissa's new fork of UFS_UTILS for the ufs_utils_develop external, which has the regional_esg_grid code (but leave the ufs_utils_chgres pointing to Larissa's old feature/chgres_grib2 branch).  That means I'll have to also have a PR into ufs-srweather-app for this change, which is partially what you did in your PR.  If that's ok, with you, I can go ahead.  Otherwise, I'll wait for your PRs to go in.  

Actually, the switch to regional_esg_grid is going to also require changes to the GSD_HRRR3km grid parameters.  That will affect the work Chunhua and Christina are doing; it will also require new orography statistics fixed files from Mike (Toy).  Looks like a mess...

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, can you start from my PRs (for regional_workflow and ufs_srweather_app) in a separate directory, then make the necessary changes to set_predef_grid_params.sh in your current directory structure where this PR sits?

We really need to merge the big UFS_UTILS PRs in soon.

**Review by JeffBeck-NOAA — APPROVED** [review]
Tested successfully on Jet (3-km, 13-km, and 25-km domains ran to completion).

**Comment by gsketefian** [comment]
@JeffBeck-NOAA Thanks for testing on Jet.  I'll merge now since Jacob seems ok with it.

**Pull request merged**
