### PR TITLE
Modify WE2E tests for NCO mode

### PR DESCRIPTION
**Pull request by chan-hoo**
## DESCRIPTION OF CHANGES: 
- Since the data for the date in the previous configuration was missing, the forecast date is changed to "20190615" for FV3GFS.
- The existing WE2E tests for the 'nco' mode are simplified and rearranged to six RRFS CONUS cases.
- FV3GFS uses COMINgfs while HRRR/RAP uses the user staged external files.

## TESTS CONDUCTED: 
New WE2E tests for the 'nco' mode:
- nco_grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
- nco_grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
- nco_grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2
- nco_grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_HRRR
- nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
- nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16

## ISSUE: 
Fixes issue mentioned in #628

### CODE REVIEW

**Comment by JeffBeck-NOAA** [comment]
@chan-hoo, I'm fine with modifying the WE2E tests, I just want to make sure that the changes to the physics suites is what we should do, when the original issue you mention in this PR is missing data/simplification of the WE2E tests.  I see you removed a GFSv16 suite test and modified another that used FV3_HRRR to use GFSv15p2.  Was there a reason to use GFSv15p2 instead?  I know we still want to test the GFSv16 and FV3_HRRR SDFs.  Just checking, and thank you for simplifying, things!

**Comment by chan-hoo** [comment]
@JeffBeck-NOAA, Should we test various physics suites for NCO mode in WE2E again? In my opinion, since they are tested in the community mode, we don't need to test them in the nco mode again. The difference between community and nco modes is the structure (location) of the input and output data. I used one physics suite to minimize the number of variables. The more the number of tests are, the harder the scripts are managed :):) What do you think? If you still need the tests for other suites, I'll add them to the list.

**Comment by chan-hoo** [comment]
@JeffBeck-NOAA, I've added two tests for GFSv16 and FV3-HRRR (and removed two GFSv15p2 using HRRR/RAP).

**Comment by JeffBeck-NOAA** [comment]
@chan-hoo, now that you mention it, I agree with you that the nco mode WE2E configurations should really be designed to test the directory/file structure and not the physics suites, since that's done in the community WE2E tests.  I see that you went ahead and replaced two of the nco tests with GFSv16 and FV3-HRRR SDFs.  If you're comfortable with those changes or would like to revert, I could go either way.  In either case, I will approve the PR now.  Thanks!

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
